/**
 * Definición de datos del menú lateral del HIS.
 *
 * Este archivo contiene SOLO data (tipos + array SECTIONS).
 * La lógica de filtrado por rol/servicio vive en `nav-visibility.ts`.
 * El rendering vive en `app-shell.tsx`.
 *
 * Separado de `app-shell.tsx` para que la Tarea 2b (Shadcn sidebar) pueda
 * consumir SECTIONS sin importar el componente React monolítico.
 */

import * as React from "react";
import {
  LayoutDashboard,
  Users,
  Bed,
  BedDouble,
  Stethoscope,
  ClipboardList,
  Building2,
  Settings,
  History,
  HeartPulse,
  HeartHandshake,
  Pill,
  FlaskConical,
  Activity,
  Scissors,
  Wind,
  Apple,
  Image as ImageIcon,
  ScanLine,
  Calendar,
  BellRing,
  Globe,
  Coins,
  MapPin,
  BookOpen,
  Wrench,
  ShieldCheck,
  Boxes,
  FileSignature,
  Skull,
  ShieldAlert,
  KeyRound,
  Gauge,
  BarChart3,
  Layers,
  ClipboardCheck,
  FileText,
  FilePenLine,
  BadgeCheck,
  GitBranch,
  Thermometer,
  NotebookPen,
  Siren,
  ArrowLeftRight,
  CheckSquare,
  UserCheck,
  Baby,
  Package,
  Truck,
  Undo2,
  Search,
  LayoutGrid,
  Zap,
  FileBadge,
  Paperclip,
  ClipboardPlus,
  TriangleAlert,
  Inbox,
  BriefcaseMedical,
  UserCog,
} from "lucide-react";
import { type NavItemVisibility } from "./nav-visibility";

export interface NavItem extends NavItemVisibility {
  href: string;
  label: string;
  icon: React.ComponentType<{ className?: string }>;
  /** Descripción corta para tooltip — explica qué hace la pantalla y a qué proceso pertenece. */
  description: string;
}

export interface NavSection {
  label: string;
  items: NavItem[];
  defaultOpen?: boolean;
}

export const SECTIONS: NavSection[] = [
  {
    label: "Visión",
    defaultOpen: true,
    items: [
      { href: "/dashboard", label: "Dashboard", icon: LayoutDashboard,
        description: "Pantalla de inicio. Resumen general de actividad del día y accesos rápidos." },
      { href: "/analytics", label: "Analítica BI", icon: BarChart3,
        description: "Reportes BI embebidos con KPIs operacionales y financieros." },
      { href: "/analytics/ejecutivo", label: "Dashboard Ejecutivo KPI", icon: Gauge,
        description: "Tablero ejecutivo con 36 KPIs en 7 categorías (clínicos, financieros, gobierno)." },
      { href: "/feedback", label: "Mi feedback (NPS)", icon: HeartHandshake,
        description: "Encuestas de satisfacción del personal (NPS) y comentarios." },
      { href: "/tareas", label: "Mi Bandeja (BPM)", icon: Inbox,
        description: "Bandeja centralizada de tareas pendientes según rol (BPM). 29 fuentes: recetas, NTEC, JCI, quirófano." },
    ],
  },
  {
    label: "Clínico",
    defaultOpen: true,
    items: [
      { href: "/patients", label: "Pacientes", icon: Users,
        description: "Registro maestro de pacientes (MPI). Búsqueda, alta, edición y deduplicación." },
      { href: "/admission", label: "Admisión", icon: ClipboardList,
        description: "Proceso de admisión: registra el ingreso del paciente al hospital." },
      { href: "/beds", label: "Camas", icon: Bed,
        description: "Mapa de camas por servicio. Asignación, libre/ocupado, limpieza." },
      { href: "/census", label: "Censo", icon: Activity,
        description: "Censo en tiempo real de pacientes hospitalizados por servicio." },
      { href: "/transfers", label: "Traslados", icon: Layers,
        description: "Traslados internos entre servicios y traslados externos a otros centros." },
      { href: "/triage", label: "Triage", icon: Stethoscope,
        requiredServiceUnits: ["ER"],
        description: "Triage Manchester en emergencias. Clasifica pacientes por urgencia (RED/ORANGE/YELLOW/GREEN/BLUE)." },
      { href: "/triage/monitor", label: "Monitor Triage", icon: Activity,
        requiredServiceUnits: ["ER"],
        description: "Wallboard kanban para TV: 5 columnas Manchester + sexo magenta/cian + paso del proceso." },
      { href: "/emergency", label: "Emergencias", icon: HeartPulse,
        requiredServiceUnits: ["ER"],
        description: "Atención de emergencia: visitas, motivos de consulta y desenlaces." },
      { href: "/outpatient", label: "Consulta externa", icon: Calendar,
        requiredServiceUnits: ["CE"],
        description: "Agendas y citas de consulta externa programada." },
      { href: "/ece/rectificaciones", label: "ECE Rectificaciones", icon: FilePenLine,
        description: "Solicitudes de rectificación de documentos ECE firmados (Art. 40 NTEC)." },
    ],
  },
  {
    label: "ECE — Atención",
    defaultOpen: true,
    items: [
      { href: "/ece/signos-vitales", label: "Signos Vitales", icon: Thermometer,
        description: "Captura y tendencias de signos vitales (PA, FC, FR, T°, SpO2, dolor)." },
      { href: "/ece/indicaciones", label: "Indicaciones Médicas", icon: ClipboardCheck,
        description: "Indicaciones médicas a personal de enfermería. Validación BCMA al ejecutar." },
      { href: "/ece/valoracion-inicial-enfermeria", label: "Valoración Inicial ENF", icon: NotebookPen,
        description: "Primera valoración de enfermería al ingreso del paciente (NTEC)." },
      { href: "/ece/registro-enfermeria", label: "Registro Enfermería", icon: ClipboardCheck,
        description: "Notas de enfermería por turno con plan de cuidados." },
      { href: "/ece/evolucion", label: "Evolución Médica", icon: NotebookPen,
        description: "Notas de evolución médica diarias durante la hospitalización." },
    ],
  },
  {
    label: "Diagnóstico",
    defaultOpen: true,
    items: [
      { href: "/ece/estudios", label: "Estudios ECE", icon: FlaskConical,
        description: "Solicitudes y resultados de estudios diagnósticos centralizados." },
      { href: "/pharmacy", label: "Farmacia", icon: Pill,
        requiredServiceUnits: ["FAR"],
        description: "Despacho de medicamentos. Validación de prescripción y stock." },
      { href: "/emar", label: "eMAR", icon: ScanLine,
        description: "Registro electrónico de administración de medicamentos (5 correctos + BCMA)." },
      { href: "/lis/results", label: "Laboratorio (LIS)", icon: FlaskConical,
        requiredServiceUnits: ["LAB"],
        description: "Resultados de laboratorio clínico, rangos de referencia y validación." },
      { href: "/imaging", label: "Imágenes (RIS)", icon: ImageIcon,
        requiredServiceUnits: ["RX"],
        description: "Estudios radiológicos: solicitudes, programación, reportes." },
      { href: "/respiratory", label: "Respiratorio", icon: Wind,
        description: "Terapia respiratoria: ventilación, nebulizaciones, oxigenoterapia." },
      { href: "/nutrition", label: "Nutrición", icon: Apple,
        description: "Plan nutricional enteral/parenteral y dietas hospitalarias." },
    ],
  },
  {
    label: "ECE — Quirófano",
    defaultOpen: true,
    items: [
      { href: "/ece/quirofano", label: "Dashboard Quirófano", icon: LayoutGrid,
        requiredServiceUnits: ["QX"],
        description: "Vista general de salas, casos del día y estado del proceso quirúrgico." },
      { href: "/surgery", label: "Quirófano", icon: Scissors,
        requiredServiceUnits: ["QX"],
        description: "Listado de casos quirúrgicos: pendientes, en curso, completados." },
      { href: "/ece/quirofano/preop", label: "Preoperatorio", icon: ClipboardList,
        requiredServiceUnits: ["QX"],
        description: "Valoración preoperatoria: riesgo anestésico, exámenes, ayuno." },
      { href: "/ece/quirofano/who-check", label: "WHO Checklist", icon: CheckSquare,
        requiredServiceUnits: ["QX"],
        description: "Lista de verificación OMS para cirugía segura (IPSG.4 JCI)." },
      { href: "/ece/quirofano/programacion", label: "Programación", icon: Scissors,
        requiredServiceUnits: ["QX"],
        description: "Programación de cirugías por sala, fecha y equipo médico." },
      { href: "/ece/quirofano/acto-quirurgico", label: "Acto Quirúrgico", icon: Zap,
        requiredServiceUnits: ["QX"],
        description: "Registro del acto quirúrgico: tiempos, equipo, hallazgos, procedimientos." },
      { href: "/ece/quirofano/consentimiento-qx", label: "Consentimiento Qx", icon: FileSignature,
        requiredServiceUnits: ["QX"],
        description: "Consentimiento informado para procedimiento quirúrgico (NTEC, doble firma)." },
      { href: "/ece/registro-anestesico", label: "Anestésico", icon: Wind,
        requiredServiceUnits: ["QX"],
        description: "Registro anestésico: medicamentos, ventilación, signos durante cirugía." },
      { href: "/ece/urpa", label: "URPA", icon: UserCheck,
        requiredServiceUnits: ["QX", "URPA"],
        description: "Unidad de Recuperación Post-Anestésica: monitoreo y criterios de egreso." },
    ],
  },
  {
    label: "ECE — Hospitalario",
    defaultOpen: true,
    items: [
      { href: "/ece/hoja-ingreso", label: "Hoja de Ingreso", icon: ClipboardList,
        description: "Documento NTEC de ingreso hospitalario con motivo, antecedentes y plan." },
      { href: "/ece/episodio-hospitalario", label: "Episodio Hospitalario", icon: BedDouble,
        description: "Vista unificada del episodio: documentos, órdenes, evolución y dependencias." },
    ],
  },
  {
    label: "ECE — Documentos",
    defaultOpen: true,
    items: [
      { href: "/ece/historia-clinica", label: "Historia Clínica", icon: FileText,
        description: "Historia clínica completa del paciente: anamnesis, antecedentes, exámenes." },
      { href: "/ece/consentimiento", label: "Consentimientos médicos (NTEC)", icon: FileSignature,
        description: "Consentimientos médicos informados según NTEC (HOSPITALIZACION, QUIRURGICO)." },
      { href: "/ece/epicrisis", label: "Epicrisis", icon: ClipboardList,
        description: "Resumen clínico al alta: diagnósticos, tratamiento, plan de seguimiento." },
      { href: "/ece/atencion-emergencia", label: "Atención Emergencia", icon: Siren,
        requiredServiceUnits: ["ER"],
        description: "Documento NTEC de atención en sala de emergencias." },
      { href: "/ece/rri", label: "RRI", icon: ArrowLeftRight,
        description: "Referencia, Retorno e Interconsulta entre servicios o centros." },
      { href: "/ece/orden-ingreso", label: "Orden de Ingreso", icon: ClipboardPlus,
        description: "Orden médica de ingreso hospitalario, formaliza la admisión." },
      { href: "/ece/certificado-incapacidad", label: "Certificado Incapacidad ISSS", icon: FileBadge,
        description: "Certificado de incapacidad para trabajadores cubiertos por ISSS." },
      { href: "/ece/documento-asociado", label: "Documentos Asociados", icon: Paperclip,
        description: "Documentos adjuntos al episodio (autorización, exámenes externos, etc.)." },
      { href: "/ece/fall-event", label: "Reporte de Caídas (IPSG.6)", icon: TriangleAlert,
        description: "Reporte de evento de caída del paciente. Cumple IPSG.6 JCI." },
    ],
  },
  {
    label: "GS1 Logística",
    defaultOpen: false,
    items: [
      { href: "/gs1/inbound", label: "Inbound", icon: Package,
        description: "Recepción de mercadería con códigos GS1 (GTIN, lote, vencimiento)." },
      { href: "/gs1/transfers", label: "Transfers", icon: Truck,
        description: "Movimientos de stock entre almacenes con trazabilidad GS1." },
      { href: "/pharmacy/unidosis", label: "Unidosis", icon: Pill,
        description: "Preparación de dosis unitarias por paciente para administración bedside." },
      { href: "/gs1/devoluciones", label: "Devoluciones", icon: Undo2,
        description: "Devoluciones de medicamentos no administrados con trazabilidad de lote." },
      { href: "/gs1/trazabilidad", label: "Trazabilidad", icon: Search,
        description: "Trazabilidad completa de lote: del proveedor al paciente (EPCIS)." },
      { href: "/gs1/gln", label: "GLN Jerarquía", icon: Layers,
        description: "Catálogo de localizaciones físicas con identificadores GLN GS1." },
      { href: "/gs1/medicamentos", label: "Medicamentos GS1", icon: Pill,
        description: "Maestro de medicamentos con códigos GTIN y mapeo NDC/CUM." },
      { href: "/gs1/dashboard", label: "Dashboard GS1", icon: BarChart3,
        description: "KPIs de adopción GS1: cobertura GTIN, escaneos, retiros de lote." },
    ],
  },
  {
    label: "Bedside (BCMA)",
    defaultOpen: false,
    items: [
      { href: "/bedside", label: "Cola Bedside", icon: ScanLine,
        description: "Cola de tareas pendientes en cabecera de paciente (medicación, signos)." },
      { href: "/pharmacy/dispense", label: "Dispensación Farmacia", icon: Pill,
        description: "Dispensación de medicamentos validada por GS1 antes de salir de farmacia." },
      { href: "/pharmacy/cart", label: "Carrito Unidosis", icon: Boxes,
        description: "Armado de carrito unidosis por turno para administración por enfermería." },
      { href: "/enfermeria/recepcion-farmacia", label: "Recepción Farmacia", icon: Truck,
        description: "Recepción y validación del carrito de farmacia en cada servicio." },
      { href: "/patient-id", label: "ID Paciente (GSRN)", icon: ScanLine,
        description: "Identificación del paciente vía brazalete GSRN GS1 (IPSG.1)." },
      { href: "/ece/kardex", label: "Kardex eMAR", icon: ClipboardCheck,
        description: "Kardex de medicación por paciente con historial de administraciones." },
      { href: "/medico/substitutions-pending", label: "Sustituciones Pendientes", icon: ArrowLeftRight,
        description: "Sustituciones farmacológicas pendientes de aprobación médica." },
    ],
  },
  {
    label: "ECE — Maternidad",
    defaultOpen: true,
    items: [
      { href: "/ece/obstetricia", label: "Dashboard Maternidad", icon: LayoutGrid,
        requiredServiceUnits: ["PARTOS", "GYN_OB"],
        description: "Tablero del servicio de obstetricia: trabajo de parto, expulsión, post-parto." },
      { href: "/ece/obstetricia/expulsion", label: "Sala Expulsión", icon: BedDouble,
        requiredServiceUnits: ["PARTOS", "GYN_OB"],
        description: "Sala de expulsión: progreso del parto, tipo de parto, complicaciones." },
      { href: "/ece/obstetricia/partograma", label: "Partograma", icon: Activity,
        requiredServiceUnits: ["PARTOS", "GYN_OB"],
        description: "Curva del trabajo de parto: dilatación, descenso, contracciones." },
      { href: "/ece/atencion-rn", label: "Atención RN", icon: Baby,
        requiredServiceUnits: ["PARTOS", "GYN_OB", "UCIN", "NEO"],
        description: "Atención inmediata del recién nacido: APGAR, antropometría, alta." },
      { href: "/ece/reanimacion-neonatal", label: "Reanimación NRP", icon: HeartHandshake,
        requiredServiceUnits: ["PARTOS", "GYN_OB", "UCIN", "NEO"],
        description: "Reanimación neonatal según protocolo NRP/AHA." },
    ],
  },
  {
    label: "Soporte clínico",
    defaultOpen: false,
    items: [
      { href: "/equipment", label: "Equipos médicos", icon: Wrench,
        description: "Inventario de equipos biomédicos con calibración y mantenimiento." },
      { href: "/inventory", label: "Inventario", icon: Boxes,
        description: "Inventario de insumos médicos y stock por bodega." },
      { href: "/insurance", label: "Aseguradoras", icon: ShieldCheck,
        description: "Catálogo de aseguradoras: pólizas, coberturas, deducibles." },
      { href: "/consents", label: "Consentimientos de datos (GDPR)", icon: FileSignature,
        description: "Consentimientos de tratamiento de datos personales (GDPR/LOPD)." },
      { href: "/deaths", label: "Defunciones", icon: Skull,
        description: "Registro de defunciones con CIE-10 y certificado de defunción." },
      { href: "/ledgers", label: "Contabilidad", icon: BookOpen,
        description: "Libros contables (FISCAL_SV / MANAGEMENT) y asientos." },
      { href: "/finance", label: "Resumen Financiero", icon: LayoutDashboard,
        description: "Landing del módulo finanzas: KPIs y accesos rápidos." },
      { href: "/finance/cost-centers", label: "Centros de Costo", icon: Building2,
        description: "41 centros de costo NTEC (productivos / intermedios / apoyo)." },
      { href: "/finance/price-lists", label: "Tarifario de Servicios", icon: BookOpen,
        description: "Tarifario de servicios clínicos. Auto-fill en facturación." },
      { href: "/finance/invoices", label: "Facturas", icon: FileText,
        description: "Emisión y consulta de facturas con imputación a centro de costo." },
      { href: "/finance/operating-costs", label: "Costos Operativos HIS", icon: Coins,
        description: "Costos operativos hospitalarios mensuales para prorrateo." },
      { href: "/finance/allocation-rules", label: "Reglas de Prorrateo", icon: GitBranch,
        description: "Configuración de reglas de prorrateo entre centros (suma = 100%)." },
      { href: "/finance/reportes", label: "Reportes Financieros", icon: BarChart3,
        description: "7 reportes regulatorios MINSAL: estado de resultados, costo por paciente, etc." },
      { href: "/notifications", label: "Notificaciones", icon: BellRing,
        description: "Centro de notificaciones del usuario: alertas y eventos del sistema." },
    ],
  },
  {
    label: "Administración",
    defaultOpen: false,
    items: [
      { href: "/organizations", label: "Organizaciones", icon: Building2,
        description: "Multi-tenancy: organizaciones y establecimientos del grupo Avante." },
      { href: "/users", label: "Usuarios", icon: Users,
        description: "Gestión de usuarios del sistema, membresías y estado." },
      { href: "/medicos", label: "Médicos", icon: BriefcaseMedical,
        description: "Catálogo B2B2C de médicos del complejo: cabecera, turno, especialistas, interconsultantes." },
      { href: "/profesionales-salud", label: "Profesionales de la Salud", icon: UserCog,
        description: "Personal no-médico: enfermería, archivo (ESDOMED), atención al cliente, administrativos." },
      { href: "/chat-analytics", label: "Asistente — Analytics", icon: BarChart3,
        description: "Telemetría del Avante Asistente: sesiones, preguntas frecuentes, satisfacción, costo." },
      { href: "/email-test", label: "Diagnóstico SMTP", icon: BellRing,
        requiredRoles: ["ADMIN", "DIRECTOR", "DIR"],
        description: "Prueba el envío de correos hacia Microsoft 365. Útil para validar configuración tras cambiar credenciales." },
      { href: "/odoo-introspect", label: "Introspección Odoo", icon: Layers,
        requiredRoles: ["ADMIN", "DIRECTOR", "DIR"],
        description: "Lee el esquema de res.partner en Odoo (READ-ONLY) para diseñar la réplica de campos del paciente en el HIS local." },
      { href: "/roles", label: "Roles y permisos", icon: KeyRound,
        description: "Catálogo de roles RBAC y permisos asignados por rol." },
      { href: "/asignaciones-servicio", label: "Asignaciones a servicio", icon: UserCog,
        requiredRoles: ["ADMIN", "DIR", "DIRECTOR", "MEDICAL_DIRECTOR"],
        description: "Nivel A — asigna usuarios a servicios (Emergencias, Quirófano, etc.). Filtra el menú y futuro data layer por servicio." },
      { href: "/abac", label: "Políticas ABAC", icon: ShieldAlert,
        description: "Políticas de control de acceso basadas en atributos." },
      { href: "/audit", label: "Auditoría", icon: History,
        description: "Bitácora de auditoría inmutable con hash chain (retención 10 años)." },
      { href: "/catalogs/gender", label: "Catálogos", icon: Settings,
        description: "Catálogos transversales: sexo biológico, género, estado civil, etc." },
      { href: "/countries", label: "Países", icon: Globe,
        description: "Configuración por país: validadores, identificadores, divisa." },
      { href: "/exchange-rates", label: "Tipos de cambio", icon: Coins,
        description: "Tipos de cambio históricos para conversión multi-moneda." },
      { href: "/sv-localization", label: "Localización SV", icon: MapPin,
        description: "Catálogos localizados El Salvador: departamentos, municipios, feriados." },
      { href: "/triage-config", label: "Config. Triage", icon: Stethoscope,
        description: "Configuración Manchester: niveles, flujogramas, discriminadores." },
      { href: "/sso-config", label: "SSO", icon: KeyRound,
        description: "Configuración de Single Sign-On (SAML / OIDC) para corporativos." },
      { href: "/slos", label: "SLOs", icon: Gauge,
        description: "Service Level Objectives: cumplimiento, error budgets." },
      { href: "/settings/notifications", label: "Preferencias notif.", icon: Settings,
        description: "Preferencias de notificación por usuario (email, push, in-app)." },
      { href: "/ece/bitacora", label: "Bitácora ECE", icon: ClipboardCheck,
        description: "Bitácora de eventos ECE (creación, firma, validación de documentos)." },
      { href: "/ece/rectificaciones/cola", label: "ECE Cola DIR", icon: FilePenLine,
        description: "Cola de rectificaciones ECE pendientes de aprobación DIR." },
      { href: "/ece/certificacion", label: "Certificación DIR", icon: BadgeCheck,
        requiredRoles: ["DIR"],
        description: "Certificación de documentos ECE por Director (Art. NTEC)." },
      { href: "/workflow-designer", label: "Workflow Designer", icon: GitBranch,
        description: "Diseñador WYSIWYG de workflows ECE: estados, transiciones, dependencias." },
      { href: "/staff-gsrn", label: "GSRN Personal", icon: BadgeCheck,
        requiredRoles: ["ADMIN_CLINICO", "ADMIN"],
        description: "Asignación de GSRN GS1 al personal clínico." },
      { href: "/farmacovigilancia", label: "Farmacovigilancia", icon: ShieldAlert,
        requiredRoles: ["ADMIN", "PHARM", "DIRECTOR"],
        description: "Reportes de reacciones adversas medicamentosas (RAM)." },
    ],
  },
];
