-- =============================================================================
-- 219_lab_catalogo_v2_seed.sql — GENERADO por
-- packages/database/scripts/generate-lab-catalogo-v2-sql.mjs a partir de
-- packages/database/seed/catalogo_laboratorio_v2.json. NO editar a mano:
-- regenerar con `node packages/database/scripts/generate-lab-catalogo-v2-sql.mjs`.
--
-- Catálogo inicial del rediseño de laboratorio (mockup 2026-09):
-- 11 secciones · 9 tipos · 40 subtipos · 218 pruebas.
-- Idempotente y org-genérico (corre para todas las organizaciones).
-- Requiere sql/218 aplicado.
-- =============================================================================

-- 1. Tipos de muestra ---------------------------------------------------------
WITH orgs AS (SELECT id FROM public."Organization"),
v(name, ord) AS (VALUES
    ('Sangre y derivados', 0),
    ('Orina', 1),
    ('Heces', 2),
    ('Secreciones y exudados', 3),
    ('Líquidos corporales', 4),
    ('Tracto respiratorio', 5),
    ('Aparato reproductor', 6),
    ('Tejidos y médula', 7),
    ('Otros', 8)
)
INSERT INTO public."LabSampleType" ("organizationId", name, "displayOrder", active)
SELECT o.id, v.name, v.ord, true FROM orgs o CROSS JOIN v
ON CONFLICT ("organizationId", name)
DO UPDATE SET "displayOrder" = EXCLUDED."displayOrder", active = true;

-- 2. Subtipos de muestra ------------------------------------------------------
WITH v(tipo, name, ord) AS (VALUES
    ('Sangre y derivados', 'Sangre total (EDTA)', 0),
    ('Sangre y derivados', 'Suero', 1),
    ('Sangre y derivados', 'Plasma (citratado)', 2),
    ('Sangre y derivados', 'Sangre capilar', 3),
    ('Sangre y derivados', 'Sangre arterial', 4),
    ('Sangre y derivados', 'Hemocultivo', 5),
    ('Sangre y derivados', 'Gota gruesa / frotis', 6),
    ('Orina', 'Orina al azar', 0),
    ('Orina', 'Primera orina de la mañana', 1),
    ('Orina', 'Orina de 24 horas', 2),
    ('Orina', 'Chorro medio (urocultivo)', 3),
    ('Orina', 'Cateterizada / suprapúbica', 4),
    ('Heces', 'Heces frescas / preservante', 0),
    ('Heces', 'Muestra seriada (parásitos)', 1),
    ('Heces', 'Hisopado / raspado anal', 2),
    ('Secreciones y exudados', 'Faríngeo / nasofaríngeo', 0),
    ('Secreciones y exudados', 'Uretral / vaginal / endocervical', 1),
    ('Secreciones y exudados', 'Conjuntival / ótico', 2),
    ('Secreciones y exudados', 'Ulceras', 3),
    ('Secreciones y exudados', 'Abscesos', 4),
    ('Secreciones y exudados', 'Heridas', 5),
    ('Líquidos corporales', 'LCR', 0),
    ('Líquidos corporales', 'Sinovial (articular)', 1),
    ('Líquidos corporales', 'Amniótico', 2),
    ('Líquidos corporales', 'Pleural', 3),
    ('Líquidos corporales', 'Peritoneal', 4),
    ('Líquidos corporales', 'Pericárdico', 5),
    ('Tracto respiratorio', 'Esputo', 0),
    ('Tracto respiratorio', 'Aspirado / lavado bronquial', 1),
    ('Tracto respiratorio', 'Aspirado traqueal', 2),
    ('Aparato reproductor', 'Semen / líquido seminal', 0),
    ('Aparato reproductor', 'Secreción prostática', 1),
    ('Tejidos y médula', 'Médula ósea', 0),
    ('Tejidos y médula', 'Tejidos y biopsias', 1),
    ('Tejidos y médula', 'Raspados piel/uñas/pelo (micológico)', 2),
    ('Otros', 'Saliva', 0),
    ('Otros', 'Cálculos (litos)', 1),
    ('Otros', 'Sudor', 2),
    ('Otros', 'Uñas/cabello (toxicología)', 3),
    ('Otros', 'Ambientales / puntas de catéter', 4)
)
INSERT INTO public."LabSampleSubtype" ("organizationId", "sampleTypeId", name, "displayOrder", active)
SELECT st."organizationId", st.id, v.name, v.ord, true
FROM v JOIN public."LabSampleType" st ON st.name = v.tipo AND st."organizationId" IS NOT NULL
ON CONFLICT ("sampleTypeId", name)
DO UPDATE SET "displayOrder" = EXCLUDED."displayOrder", active = true;

-- 3. Secciones (LabPanel, area LABORATORIO) -----------------------------------
WITH orgs AS (SELECT id FROM public."Organization"),
v(name, code, ord) AS (VALUES
    ('QUIMICA', 'SECLB-01', 0),
    ('URIANALISIS', 'SECLB-02', 1),
    ('HEMATOLOGIA', 'SECLB-03', 2),
    ('PRUEBAS ESPECIALES', 'SECLB-04', 3),
    ('COAGULACION', 'SECLB-05', 4),
    ('COPROLOGIA', 'SECLB-06', 5),
    ('INMUNOLOGIA/SEROLOGIA', 'SECLB-07', 6),
    ('MICROBIOLOGIA', 'SECLB-08', 7),
    ('INMUNO-HEMATOLOGIA', 'SECLB-09', 8),
    ('BIOLOGIA MOLECULAR', 'SECLB-10', 9),
    ('CITOPATOLOGIA', 'SECLB-11', 10)
)
INSERT INTO public."LabPanel" (id, "organizationId", code, name, area, "displayOrder", active, "createdAt", "updatedAt")
SELECT gen_random_uuid(), o.id, v.code, v.name, 'LABORATORIO', v.ord, true, now(), now()
FROM orgs o CROSS JOIN v
WHERE NOT EXISTS (
  SELECT 1 FROM public."LabPanel" p
  WHERE p."organizationId" = o.id AND upper(p.name) = upper(v.name) AND p.area = 'LABORATORIO');

UPDATE public."LabPanel" p SET "displayOrder" = v.ord, active = true, "updatedAt" = now()
FROM (VALUES
    ('QUIMICA', 'SECLB-01', 0),
    ('URIANALISIS', 'SECLB-02', 1),
    ('HEMATOLOGIA', 'SECLB-03', 2),
    ('PRUEBAS ESPECIALES', 'SECLB-04', 3),
    ('COAGULACION', 'SECLB-05', 4),
    ('COPROLOGIA', 'SECLB-06', 5),
    ('INMUNOLOGIA/SEROLOGIA', 'SECLB-07', 6),
    ('MICROBIOLOGIA', 'SECLB-08', 7),
    ('INMUNO-HEMATOLOGIA', 'SECLB-09', 8),
    ('BIOLOGIA MOLECULAR', 'SECLB-10', 9),
    ('CITOPATOLOGIA', 'SECLB-11', 10)
) AS v(name, code, ord)
WHERE p."organizationId" IS NOT NULL AND p.area = 'LABORATORIO' AND upper(p.name) = upper(v.name);

-- 4. Pruebas (LabTest) --------------------------------------------------------
-- 4a. Actualizar existentes (match por org + sección + nombre, case-insensitive).
WITH v(seccion, prueba, tipo, subtipo, cant, code, ord) AS (VALUES
    ('PRUEBAS ESPECIALES', 'AC HEPATITIS C', 'Sangre y derivados', 'Suero', 1, 'LABV2-001', 0),
    ('QUIMICA', 'ACIDO URICO', 'Sangre y derivados', 'Suero', 1, 'LABV2-002', 1),
    ('URIANALISIS', 'ACIDO URICO', 'Orina', 'Orina al azar', 1, 'LABV2-003', 2),
    ('PRUEBAS ESPECIALES', 'AG AUSTRALIANO HEP B', 'Sangre y derivados', 'Suero', 1, 'LABV2-004', 3),
    ('COPROLOGIA', 'AG HELICOBACTER PYLORI', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-005', 4),
    ('INMUNO-HEMATOLOGIA', 'AGLUTININAS', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-006', 5),
    ('QUIMICA', 'ALBUMINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-007', 6),
    ('PRUEBAS ESPECIALES', 'ALFA FETO PROTEINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-008', 7),
    ('QUIMICA', 'AMILASA', 'Sangre y derivados', 'Suero', 1, 'LABV2-009', 8),
    ('URIANALISIS', 'AMILASA', 'Orina', 'Orina al azar', 1, 'LABV2-010', 9),
    ('QUIMICA', 'AMONIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-011', 10),
    ('COAGULACION', 'ANTICOAGULANTE LUPICO', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-012', 11),
    ('INMUNOLOGIA/SEROLOGIA', 'ANTICUERPOS ANTINUCLEARES', 'Sangre y derivados', 'Suero', 1, 'LABV2-013', 12),
    ('INMUNOLOGIA/SEROLOGIA', 'ANTICUERPOS HELICOBACTER PYLORI', 'Sangre y derivados', 'Suero', 1, 'LABV2-014', 13),
    ('INMUNO-HEMATOLOGIA', 'ANTICUERPOS IRREGULARES', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-015', 14),
    ('INMUNOLOGIA/SEROLOGIA', 'ANTIGENO COVID 19', 'Secreciones y exudados', 'Faríngeo / nasofaríngeo', 1, 'LABV2-016', 15),
    ('COPROLOGIA', 'ANTIGENO PARA SALMONELLA', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-017', 16),
    ('INMUNOLOGIA/SEROLOGIA', 'ANTIGENOS FEBRILES', 'Sangre y derivados', 'Suero', 1, 'LABV2-018', 17),
    ('COPROLOGIA', 'AZUL DE METILENO', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-019', 18),
    ('MICROBIOLOGIA', 'BACILOSCOPIA', 'Tracto respiratorio', 'Esputo', 1, 'LABV2-020', 19),
    ('QUIMICA', 'BILIRRUBINA DIRECTA', 'Sangre y derivados', 'Suero', 1, 'LABV2-021', 20),
    ('QUIMICA', 'BILIRRUBINA INDIRECTA', 'Sangre y derivados', 'Suero', 1, 'LABV2-022', 21),
    ('QUIMICA', 'BILIRRUBINA TOTAL', 'Sangre y derivados', 'Suero', 1, 'LABV2-023', 22),
    ('PRUEBAS ESPECIALES', 'CA 19-9', 'Sangre y derivados', 'Suero', 1, 'LABV2-024', 23),
    ('QUIMICA', 'CALCIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-025', 24),
    ('URIANALISIS', 'CALCIO', 'Orina', 'Orina al azar', 1, 'LABV2-026', 25),
    ('PRUEBAS ESPECIALES', 'ANTIGENO CARCINOEMBRIONARIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-027', 26),
    ('PRUEBAS ESPECIALES', 'CHAGAS', 'Sangre y derivados', 'Suero', 1, 'LABV2-028', 27),
    ('QUIMICA', 'CITOQUIMICO DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-029', 28),
    ('PRUEBAS ESPECIALES', 'CK-MB', 'Sangre y derivados', 'Suero', 1, 'LABV2-030', 29),
    ('QUIMICA', 'CPK-TOTAL', 'Sangre y derivados', 'Suero', 1, 'LABV2-031', 30),
    ('QUIMICA', 'CLORO', 'Sangre y derivados', 'Suero', 1, 'LABV2-032', 31),
    ('URIANALISIS', 'CLORO', 'Orina', 'Orina al azar', 1, 'LABV2-033', 32),
    ('COPROLOGIA', 'CLOSTRIDIUM-PRUEBA RAPIDA', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-034', 33),
    ('QUIMICA', 'COLESTEROL', 'Sangre y derivados', 'Suero', 1, 'LABV2-035', 34),
    ('QUIMICA', 'COLESTEROL HDL', 'Sangre y derivados', 'Suero', 1, 'LABV2-036', 35),
    ('QUIMICA', 'COLESTEROL LDL', 'Sangre y derivados', 'Suero', 1, 'LABV2-037', 36),
    ('COPROLOGIA', 'COLORACION DE COCCIDIOS', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-038', 37),
    ('HEMATOLOGIA', 'COLORACION DE WRIGHT', 'Sangre y derivados', 'Gota gruesa / frotis', 1, 'LABV2-039', 38),
    ('MICROBIOLOGIA', 'COLORACION GRAM', 'Secreciones y exudados', 'Heridas', 1, 'LABV2-040', 39),
    ('MICROBIOLOGIA', 'COLORACION ZIEHL-NEELSEN', 'Tracto respiratorio', 'Esputo', 1, 'LABV2-041', 40),
    ('INMUNOLOGIA/SEROLOGIA', 'COMBO DENGUE NS1/IgG/IgM', 'Sangre y derivados', 'Suero', 1, 'LABV2-042', 41),
    ('INMUNOLOGIA/SEROLOGIA', 'COMBO IgG/IgM HEPATITIS A', 'Sangre y derivados', 'Suero', 1, 'LABV2-043', 42),
    ('INMUNOLOGIA/SEROLOGIA', 'COMBO SARAMPION IgG/IgM', 'Sangre y derivados', 'Suero', 1, 'LABV2-044', 43),
    ('COPROLOGIA', 'CONCENTRADO DE HECES', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-045', 44),
    ('HEMATOLOGIA', 'CONCENTRADO DE STROUT', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-046', 45),
    ('HEMATOLOGIA', 'CONTEO DE EOSINOFILOS', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-047', 46),
    ('INMUNO-HEMATOLOGIA', 'COOMBS DIRECTO', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-048', 47),
    ('MICROBIOLOGIA', 'COPROCULTIVO', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-049', 48),
    ('PRUEBAS ESPECIALES', 'CORTISOL', 'Sangre y derivados', 'Suero', 1, 'LABV2-050', 49),
    ('QUIMICA', 'CREATININA', 'Sangre y derivados', 'Suero', 1, 'LABV2-051', 50),
    ('URIANALISIS', 'CREATININA', 'Orina', 'Orina al azar', 1, 'LABV2-052', 51),
    ('MICROBIOLOGIA', 'CULTIVO DE ESPUTO', 'Tracto respiratorio', 'Esputo', 1, 'LABV2-053', 52),
    ('MICROBIOLOGIA', 'CULTIVO DE HERIDA OPERATORIA', 'Secreciones y exudados', 'Heridas', 1, 'LABV2-054', 53),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-055', 54),
    ('MICROBIOLOGIA', 'CULTIVO DE ULCERA', 'Secreciones y exudados', 'Heridas', 1, 'LABV2-056', 55),
    ('MICROBIOLOGIA', 'CULTIVO ESPECIFICAR PROCEDENCIA', 'Otros', 'Ambientales / puntas de catéter', 1, 'LABV2-057', 56),
    ('MICROBIOLOGIA', 'CULTIVO VAGINAL', 'Secreciones y exudados', 'Uretral / vaginal / endocervical', 1, 'LABV2-058', 57),
    ('MICROBIOLOGIA', 'CULTIVOS FARINGEO', 'Secreciones y exudados', 'Faríngeo / nasofaríngeo', 1, 'LABV2-059', 58),
    ('QUIMICA', 'CURVA TOLERANCIA GLUCOSA', 'Sangre y derivados', 'Suero', 1, 'LABV2-060', 59),
    ('URIANALISIS', 'DEPURACION DE CREATININA', 'Orina', 'Orina de 24 horas', 1, 'LABV2-061', 60),
    ('URIANALISIS', 'DEPURACION DE PROTEINAS', 'Orina', 'Orina de 24 horas', 1, 'LABV2-062', 61),
    ('COAGULACION', 'DIMERO D', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-063', 62),
    ('URIANALISIS', 'DIMORFISMO ERITROCITARIO', 'Orina', 'Orina al azar', 1, 'LABV2-064', 63),
    ('MICROBIOLOGIA', 'DIRECTO KOH', 'Tejidos y médula', 'Raspados piel/uñas/pelo (micológico)', 1, 'LABV2-065', 64),
    ('MICROBIOLOGIA', 'DIRECTO TINTA CHINA DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-066', 65),
    ('HEMATOLOGIA', 'ERITROSEDIMENTACIÓN', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-067', 66),
    ('PRUEBAS ESPECIALES', 'FACTOR REUMATOIDEO', 'Sangre y derivados', 'Suero', 1, 'LABV2-068', 67),
    ('PRUEBAS ESPECIALES', 'FERRITINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-069', 68),
    ('COAGULACION', 'FIBRINOGENO', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-070', 69),
    ('QUIMICA', 'FOSFATASA ALCATINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-071', 70),
    ('QUIMICA', 'FOSFORO', 'Sangre y derivados', 'Suero', 1, 'LABV2-072', 71),
    ('URIANALISIS', 'FOSFORO', 'Orina', 'Orina al azar', 1, 'LABV2-073', 72),
    ('HEMATOLOGIA', 'FROTIS DE SANGRE PERIFERICA', 'Sangre y derivados', 'Gota gruesa / frotis', 1, 'LABV2-074', 73),
    ('QUIMICA', 'GAMMA-GT', 'Sangre y derivados', 'Suero', 1, 'LABV2-075', 74),
    ('COPROLOGIA', 'GENERAL DE HECES', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-076', 75),
    ('URIANALISIS', 'GENERAL DE ORINA', 'Orina', 'Primera orina de la mañana', 1, 'LABV2-077', 76),
    ('QUIMICA', 'GLOBULINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-078', 77),
    ('QUIMICA', 'GLUCOSA', 'Sangre y derivados', 'Suero', 1, 'LABV2-079', 78),
    ('URIANALISIS', 'GLUCOSA', 'Orina', 'Orina al azar', 1, 'LABV2-080', 79),
    ('HEMATOLOGIA', 'GOTA GRUESA', 'Sangre y derivados', 'Gota gruesa / frotis', 1, 'LABV2-081', 80),
    ('MICROBIOLOGIA', 'HEMOCULTIVOS', 'Sangre y derivados', 'Hemocultivo', 2, 'LABV2-082', 81),
    ('PRUEBAS ESPECIALES', 'HEMOGLOBINA GLICOSILADA', 'Sangre y derivados', 'Suero', 1, 'LABV2-083', 82),
    ('HEMATOLOGIA', 'HEMOGRAMA COMPLETO', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-084', 83),
    ('QUIMICA', 'HIERRO', 'Sangre y derivados', 'Suero', 1, 'LABV2-085', 84),
    ('PRUEBAS ESPECIALES', 'HIV CUARTA GENERACIÓN', 'Sangre y derivados', 'Suero', 1, 'LABV2-086', 85),
    ('INMUNOLOGIA/SEROLOGIA', 'HIV-RAPIDO', 'Sangre y derivados', 'Suero', 1, 'LABV2-087', 86),
    ('HEMATOLOGIA', 'INDUCCIÓN DE DREPANOCITOS', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-088', 87),
    ('INMUNOLOGIA/SEROLOGIA', 'INFLUENZA Ag A/B/H1N1', 'Secreciones y exudados', 'Faríngeo / nasofaríngeo', 1, 'LABV2-089', 88),
    ('PRUEBAS ESPECIALES', 'INSULINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-090', 89),
    ('QUIMICA', 'LACTATO DESHIDROGENASA', 'Sangre y derivados', 'Suero', 1, 'LABV2-091', 90),
    ('INMUNOLOGIA/SEROLOGIA', 'LATEX-FACTOR REUMATOIDEO', 'Sangre y derivados', 'Suero', 1, 'LABV2-092', 91),
    ('QUIMICA', 'LIPASA', 'Sangre y derivados', 'Suero', 1, 'LABV2-093', 92),
    ('QUIMICA', 'MAGNESIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-094', 93),
    ('URIANALISIS', 'MAGNESIO', 'Orina', 'Orina al azar', 1, 'LABV2-095', 94),
    ('PRUEBAS ESPECIALES', 'MIOGLOBINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-096', 95),
    ('INMUNOLOGIA/SEROLOGIA', 'MONOTEST', 'Sangre y derivados', 'Suero', 1, 'LABV2-097', 96),
    ('QUIMICA', 'NITROGENO UREICO', 'Sangre y derivados', 'Suero', 1, 'LABV2-098', 97),
    ('URIANALISIS', 'NITROGENO UREICO', 'Orina', 'Orina al azar', 1, 'LABV2-099', 98),
    ('BIOLOGIA MOLECULAR', 'PANEL DE INFECCION', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-100', 99),
    ('BIOLOGIA MOLECULAR', 'PANEL DE SEPSIS', 'Sangre y derivados', 'Hemocultivo', 1, 'LABV2-101', 100),
    ('COPROLOGIA', 'PANEL GASTRICO VIRAL', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-102', 101),
    ('BIOLOGIA MOLECULAR', 'PANEL GASTROINTESTINAL', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-103', 102),
    ('INMUNOLOGIA/SEROLOGIA', 'PANEL ITS RAPIDO', 'Sangre y derivados', 'Suero', 1, 'LABV2-104', 103),
    ('BIOLOGIA MOLECULAR', 'PANEL MENINGITIS/ENCEFALITIS', 'Líquidos corporales', 'LCR', 1, 'LABV2-105', 104),
    ('INMUNOLOGIA/SEROLOGIA', 'PANEL RAPIDO ARBOVIRUS', 'Sangre y derivados', 'Suero', 1, 'LABV2-106', 105),
    ('URIANALISIS', 'PANEL RAPIDO DE DROGAS', 'Orina', 'Orina al azar', 1, 'LABV2-107', 106),
    ('BIOLOGIA MOLECULAR', 'PANEL RESPIRATOIRO', 'Secreciones y exudados', 'Faríngeo / nasofaríngeo', 1, 'LABV2-108', 107),
    ('INMUNOLOGIA/SEROLOGIA', 'PANEL RESPIRATORIO RAPIDO', 'Secreciones y exudados', 'Faríngeo / nasofaríngeo', 1, 'LABV2-109', 108),
    ('BIOLOGIA MOLECULAR', 'PANELPNEUMONIA', 'Tracto respiratorio', 'Aspirado / lavado bronquial', 1, 'LABV2-110', 109),
    ('PRUEBAS ESPECIALES', 'PCR-CARDIACA', 'Sangre y derivados', 'Suero', 1, 'LABV2-111', 110),
    ('COPROLOGIA', 'PH EN HECES', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-112', 111),
    ('QUIMICA', 'POTASIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-113', 112),
    ('URIANALISIS', 'POTASIO', 'Orina', 'Orina al azar', 1, 'LABV2-114', 113),
    ('PRUEBAS ESPECIALES', 'PRO-BNP', 'Sangre y derivados', 'Suero', 1, 'LABV2-115', 114),
    ('PRUEBAS ESPECIALES', 'PROCALCITONINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-116', 115),
    ('QUIMICA', 'PROTEINA C REACTIVA', 'Sangre y derivados', 'Suero', 1, 'LABV2-117', 116),
    ('QUIMICA', 'PROTEINAS TOTALES', 'Sangre y derivados', 'Suero', 1, 'LABV2-118', 117),
    ('URIANALISIS', 'PROTEINAS TOTALES', 'Orina', 'Orina al azar', 1, 'LABV2-119', 118),
    ('INMUNOLOGIA/SEROLOGIA', 'PRUEBA ASTO-LATEX', 'Sangre y derivados', 'Suero', 1, 'LABV2-120', 119),
    ('INMUNO-HEMATOLOGIA', 'PRUEBA CRUZADA', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-121', 120),
    ('INMUNOLOGIA/SEROLOGIA', 'PRUEBA DE EMBARAZO', 'Sangre y derivados', 'Suero', 1, 'LABV2-122', 121),
    ('URIANALISIS', 'PRUEBA DE EMBARAZO', 'Orina', 'Orina al azar', 1, 'LABV2-123', 122),
    ('INMUNO-HEMATOLOGIA', 'PRUEBA DU', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-124', 123),
    ('PRUEBAS ESPECIALES', 'PSA LIBRE', 'Sangre y derivados', 'Suero', 1, 'LABV2-125', 124),
    ('PRUEBAS ESPECIALES', 'PSA TOTAL', 'Sangre y derivados', 'Suero', 1, 'LABV2-126', 125),
    ('QUIMICA', 'RELACION ALBUMINA/GLOBULINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-127', 126),
    ('HEMATOLOGIA', 'RETICULOCITOS', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-128', 127),
    ('COPROLOGIA', 'ROTAVIRUS', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-129', 128),
    ('INMUNOLOGIA/SEROLOGIA', 'RPR-CARBON', 'Sangre y derivados', 'Suero', 1, 'LABV2-130', 129),
    ('COPROLOGIA', 'SANGRE OCULTA', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-131', 130),
    ('PRUEBAS ESPECIALES', 'SIFILIS CUARTA GENERACIÓN', 'Sangre y derivados', 'Suero', 1, 'LABV2-132', 131),
    ('INMUNOLOGIA/SEROLOGIA', 'SIFILIS-RAPIDO', 'Sangre y derivados', 'Suero', 1, 'LABV2-133', 132),
    ('QUIMICA', 'SODIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-134', 133),
    ('URIANALISIS', 'SODIO', 'Orina', 'Orina al azar', 1, 'LABV2-135', 134),
    ('COPROLOGIA', 'SUDAN III', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-136', 135),
    ('COPROLOGIA', 'SUSTANCIAS REDUCTORAS', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-137', 136),
    ('PRUEBAS ESPECIALES', 'T3 LIBRE', 'Sangre y derivados', 'Suero', 1, 'LABV2-138', 137),
    ('PRUEBAS ESPECIALES', 'T3 TOTAL', 'Sangre y derivados', 'Suero', 1, 'LABV2-139', 138),
    ('PRUEBAS ESPECIALES', 'T4 LIBRE', 'Sangre y derivados', 'Suero', 1, 'LABV2-140', 139),
    ('PRUEBAS ESPECIALES', 'T4 TOTAL', 'Sangre y derivados', 'Suero', 1, 'LABV2-141', 140),
    ('QUIMICA', 'TEST ''OSULLIVAN', 'Sangre y derivados', 'Suero', 1, 'LABV2-142', 141),
    ('QUIMICA', 'TGO', 'Sangre y derivados', 'Suero', 1, 'LABV2-143', 142),
    ('QUIMICA', 'TGP', 'Sangre y derivados', 'Suero', 1, 'LABV2-144', 143),
    ('COAGULACION', 'TIEMPO DE COAGULACIÓN', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-145', 144),
    ('COAGULACION', 'TIEMPO DE PROTROMBINA', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-146', 145),
    ('COAGULACION', 'TIEMPO DE SANGRAMIENTO', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-147', 146),
    ('COAGULACION', 'TIEMPO DE TROMBINA', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-148', 147),
    ('COAGULACION', 'TIEMPO DE TROMBOPLASTINA PARCIAL', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-149', 148),
    ('INMUNO-HEMATOLOGIA', 'TIPEO SANGUINEO', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-150', 149),
    ('QUIMICA', 'TRIGLICERIDO', 'Sangre y derivados', 'Suero', 1, 'LABV2-151', 150),
    ('PRUEBAS ESPECIALES', 'TROPONINA I', 'Sangre y derivados', 'Suero', 1, 'LABV2-152', 151),
    ('PRUEBAS ESPECIALES', 'TROPONINA T', 'Sangre y derivados', 'Suero', 1, 'LABV2-153', 152),
    ('PRUEBAS ESPECIALES', 'TSH', 'Sangre y derivados', 'Suero', 1, 'LABV2-154', 153),
    ('MICROBIOLOGIA', 'UROCULTIVO', 'Orina', 'Chorro medio (urocultivo)', 1, 'LABV2-155', 154),
    ('PRUEBAS ESPECIALES', 'VITAMINA B12', 'Sangre y derivados', 'Suero', 1, 'LABV2-156', 155),
    ('PRUEBAS ESPECIALES', 'VITAMINA D', 'Sangre y derivados', 'Suero', 1, 'LABV2-157', 156),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-158', 157),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-159', 158),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-160', 159),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-161', 160),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS  DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-162', 161),
    ('QUIMICA', 'CITOQUIMICO DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-163', 162),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-164', 163),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-165', 164),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-166', 165),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-167', 166),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-168', 167),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-169', 168),
    ('QUIMICA', 'pH DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-170', 169),
    ('QUIMICA', 'TRIGLICERIDOS DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-171', 170),
    ('MICROBIOLOGIA', 'ADENOSINA DESAMINASA (ADA)', 'Líquidos corporales', 'LCR', 1, 'LABV2-172', 171),
    ('BIOLOGIA MOLECULAR', 'GENEXPERT DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-173', 172),
    ('QUIMICA', 'LACTATO DESHIDROGENASA DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-174', 173),
    ('QUIMICA', 'PROTEINAS TOTALES DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-175', 174),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-176', 175),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-177', 176),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-178', 177),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-179', 178),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-180', 179),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LIQUIDO AMNIOTICO', 'Líquidos corporales', 'Amniótico', 1, 'LABV2-181', 180),
    ('QUIMICA', 'CITOQUIMICO DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-182', 181),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-183', 182),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-184', 183),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-185', 184),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-186', 185),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-187', 186),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-188', 187),
    ('QUIMICA', 'pH DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-189', 188),
    ('QUIMICA', 'LACTATO DESHIDROGENASA DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-190', 189),
    ('QUIMICA', 'PROTEINAS TOTALES DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-191', 190),
    ('BIOLOGIA MOLECULAR', 'GENEXPERT DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-192', 191),
    ('QUIMICA', 'CITOQUIMICO DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-193', 192),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-194', 193),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-195', 194),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-196', 195),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-197', 196),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-198', 197),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-199', 198),
    ('HEMATOLOGIA', 'RECUENTO CELULAR DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-200', 199),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-201', 200),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-202', 201),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-203', 202),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-204', 203),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-205', 204),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-206', 205),
    ('QUIMICA', 'ALBUMINA DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-207', 206),
    ('QUIMICA', 'CITOQUIMICODE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-208', 207),
    ('HEMATOLOGIA', 'RECUENTO CELULAR DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-209', 208),
    ('QUIMICA', 'CITOQUIMICO DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-210', 209),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-211', 210),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-212', 211),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-213', 212),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-214', 213),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-215', 214),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-216', 215),
    ('MICROBIOLOGIA', 'COLORACION GRAM DE ULCERA', 'Secreciones y exudados', 'Ulceras', 1, 'LABV2-217', 216),
    ('MICROBIOLOGIA', 'COLORACION GRAM DE ABSCESOS', 'Secreciones y exudados', 'Ulceras', 1, 'LABV2-218', 217)
)
UPDATE public."LabTest" t SET
  "sampleTypeId"    = st.id,
  "sampleSubtypeId" = ss.id,
  "defaultQty"      = v.cant,
  "displayOrder"    = v.ord,
  active            = true,
  "updatedAt"       = now()
FROM v
JOIN public."LabPanel" p  ON p.area = 'LABORATORIO' AND upper(p.name) = upper(v.seccion)
JOIN public."LabSampleType" st ON st.name = v.tipo AND st."organizationId" = p."organizationId"
LEFT JOIN public."LabSampleSubtype" ss ON ss."sampleTypeId" = st.id AND ss.name = v.subtipo
WHERE t."panelId" = p.id AND t."organizationId" = p."organizationId"
  AND upper(t.name) = upper(v.prueba);

-- 4b. Insertar faltantes.
WITH v(seccion, prueba, tipo, subtipo, cant, code, ord) AS (VALUES
    ('PRUEBAS ESPECIALES', 'AC HEPATITIS C', 'Sangre y derivados', 'Suero', 1, 'LABV2-001', 0),
    ('QUIMICA', 'ACIDO URICO', 'Sangre y derivados', 'Suero', 1, 'LABV2-002', 1),
    ('URIANALISIS', 'ACIDO URICO', 'Orina', 'Orina al azar', 1, 'LABV2-003', 2),
    ('PRUEBAS ESPECIALES', 'AG AUSTRALIANO HEP B', 'Sangre y derivados', 'Suero', 1, 'LABV2-004', 3),
    ('COPROLOGIA', 'AG HELICOBACTER PYLORI', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-005', 4),
    ('INMUNO-HEMATOLOGIA', 'AGLUTININAS', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-006', 5),
    ('QUIMICA', 'ALBUMINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-007', 6),
    ('PRUEBAS ESPECIALES', 'ALFA FETO PROTEINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-008', 7),
    ('QUIMICA', 'AMILASA', 'Sangre y derivados', 'Suero', 1, 'LABV2-009', 8),
    ('URIANALISIS', 'AMILASA', 'Orina', 'Orina al azar', 1, 'LABV2-010', 9),
    ('QUIMICA', 'AMONIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-011', 10),
    ('COAGULACION', 'ANTICOAGULANTE LUPICO', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-012', 11),
    ('INMUNOLOGIA/SEROLOGIA', 'ANTICUERPOS ANTINUCLEARES', 'Sangre y derivados', 'Suero', 1, 'LABV2-013', 12),
    ('INMUNOLOGIA/SEROLOGIA', 'ANTICUERPOS HELICOBACTER PYLORI', 'Sangre y derivados', 'Suero', 1, 'LABV2-014', 13),
    ('INMUNO-HEMATOLOGIA', 'ANTICUERPOS IRREGULARES', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-015', 14),
    ('INMUNOLOGIA/SEROLOGIA', 'ANTIGENO COVID 19', 'Secreciones y exudados', 'Faríngeo / nasofaríngeo', 1, 'LABV2-016', 15),
    ('COPROLOGIA', 'ANTIGENO PARA SALMONELLA', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-017', 16),
    ('INMUNOLOGIA/SEROLOGIA', 'ANTIGENOS FEBRILES', 'Sangre y derivados', 'Suero', 1, 'LABV2-018', 17),
    ('COPROLOGIA', 'AZUL DE METILENO', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-019', 18),
    ('MICROBIOLOGIA', 'BACILOSCOPIA', 'Tracto respiratorio', 'Esputo', 1, 'LABV2-020', 19),
    ('QUIMICA', 'BILIRRUBINA DIRECTA', 'Sangre y derivados', 'Suero', 1, 'LABV2-021', 20),
    ('QUIMICA', 'BILIRRUBINA INDIRECTA', 'Sangre y derivados', 'Suero', 1, 'LABV2-022', 21),
    ('QUIMICA', 'BILIRRUBINA TOTAL', 'Sangre y derivados', 'Suero', 1, 'LABV2-023', 22),
    ('PRUEBAS ESPECIALES', 'CA 19-9', 'Sangre y derivados', 'Suero', 1, 'LABV2-024', 23),
    ('QUIMICA', 'CALCIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-025', 24),
    ('URIANALISIS', 'CALCIO', 'Orina', 'Orina al azar', 1, 'LABV2-026', 25),
    ('PRUEBAS ESPECIALES', 'ANTIGENO CARCINOEMBRIONARIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-027', 26),
    ('PRUEBAS ESPECIALES', 'CHAGAS', 'Sangre y derivados', 'Suero', 1, 'LABV2-028', 27),
    ('QUIMICA', 'CITOQUIMICO DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-029', 28),
    ('PRUEBAS ESPECIALES', 'CK-MB', 'Sangre y derivados', 'Suero', 1, 'LABV2-030', 29),
    ('QUIMICA', 'CPK-TOTAL', 'Sangre y derivados', 'Suero', 1, 'LABV2-031', 30),
    ('QUIMICA', 'CLORO', 'Sangre y derivados', 'Suero', 1, 'LABV2-032', 31),
    ('URIANALISIS', 'CLORO', 'Orina', 'Orina al azar', 1, 'LABV2-033', 32),
    ('COPROLOGIA', 'CLOSTRIDIUM-PRUEBA RAPIDA', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-034', 33),
    ('QUIMICA', 'COLESTEROL', 'Sangre y derivados', 'Suero', 1, 'LABV2-035', 34),
    ('QUIMICA', 'COLESTEROL HDL', 'Sangre y derivados', 'Suero', 1, 'LABV2-036', 35),
    ('QUIMICA', 'COLESTEROL LDL', 'Sangre y derivados', 'Suero', 1, 'LABV2-037', 36),
    ('COPROLOGIA', 'COLORACION DE COCCIDIOS', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-038', 37),
    ('HEMATOLOGIA', 'COLORACION DE WRIGHT', 'Sangre y derivados', 'Gota gruesa / frotis', 1, 'LABV2-039', 38),
    ('MICROBIOLOGIA', 'COLORACION GRAM', 'Secreciones y exudados', 'Heridas', 1, 'LABV2-040', 39),
    ('MICROBIOLOGIA', 'COLORACION ZIEHL-NEELSEN', 'Tracto respiratorio', 'Esputo', 1, 'LABV2-041', 40),
    ('INMUNOLOGIA/SEROLOGIA', 'COMBO DENGUE NS1/IgG/IgM', 'Sangre y derivados', 'Suero', 1, 'LABV2-042', 41),
    ('INMUNOLOGIA/SEROLOGIA', 'COMBO IgG/IgM HEPATITIS A', 'Sangre y derivados', 'Suero', 1, 'LABV2-043', 42),
    ('INMUNOLOGIA/SEROLOGIA', 'COMBO SARAMPION IgG/IgM', 'Sangre y derivados', 'Suero', 1, 'LABV2-044', 43),
    ('COPROLOGIA', 'CONCENTRADO DE HECES', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-045', 44),
    ('HEMATOLOGIA', 'CONCENTRADO DE STROUT', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-046', 45),
    ('HEMATOLOGIA', 'CONTEO DE EOSINOFILOS', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-047', 46),
    ('INMUNO-HEMATOLOGIA', 'COOMBS DIRECTO', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-048', 47),
    ('MICROBIOLOGIA', 'COPROCULTIVO', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-049', 48),
    ('PRUEBAS ESPECIALES', 'CORTISOL', 'Sangre y derivados', 'Suero', 1, 'LABV2-050', 49),
    ('QUIMICA', 'CREATININA', 'Sangre y derivados', 'Suero', 1, 'LABV2-051', 50),
    ('URIANALISIS', 'CREATININA', 'Orina', 'Orina al azar', 1, 'LABV2-052', 51),
    ('MICROBIOLOGIA', 'CULTIVO DE ESPUTO', 'Tracto respiratorio', 'Esputo', 1, 'LABV2-053', 52),
    ('MICROBIOLOGIA', 'CULTIVO DE HERIDA OPERATORIA', 'Secreciones y exudados', 'Heridas', 1, 'LABV2-054', 53),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-055', 54),
    ('MICROBIOLOGIA', 'CULTIVO DE ULCERA', 'Secreciones y exudados', 'Heridas', 1, 'LABV2-056', 55),
    ('MICROBIOLOGIA', 'CULTIVO ESPECIFICAR PROCEDENCIA', 'Otros', 'Ambientales / puntas de catéter', 1, 'LABV2-057', 56),
    ('MICROBIOLOGIA', 'CULTIVO VAGINAL', 'Secreciones y exudados', 'Uretral / vaginal / endocervical', 1, 'LABV2-058', 57),
    ('MICROBIOLOGIA', 'CULTIVOS FARINGEO', 'Secreciones y exudados', 'Faríngeo / nasofaríngeo', 1, 'LABV2-059', 58),
    ('QUIMICA', 'CURVA TOLERANCIA GLUCOSA', 'Sangre y derivados', 'Suero', 1, 'LABV2-060', 59),
    ('URIANALISIS', 'DEPURACION DE CREATININA', 'Orina', 'Orina de 24 horas', 1, 'LABV2-061', 60),
    ('URIANALISIS', 'DEPURACION DE PROTEINAS', 'Orina', 'Orina de 24 horas', 1, 'LABV2-062', 61),
    ('COAGULACION', 'DIMERO D', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-063', 62),
    ('URIANALISIS', 'DIMORFISMO ERITROCITARIO', 'Orina', 'Orina al azar', 1, 'LABV2-064', 63),
    ('MICROBIOLOGIA', 'DIRECTO KOH', 'Tejidos y médula', 'Raspados piel/uñas/pelo (micológico)', 1, 'LABV2-065', 64),
    ('MICROBIOLOGIA', 'DIRECTO TINTA CHINA DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-066', 65),
    ('HEMATOLOGIA', 'ERITROSEDIMENTACIÓN', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-067', 66),
    ('PRUEBAS ESPECIALES', 'FACTOR REUMATOIDEO', 'Sangre y derivados', 'Suero', 1, 'LABV2-068', 67),
    ('PRUEBAS ESPECIALES', 'FERRITINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-069', 68),
    ('COAGULACION', 'FIBRINOGENO', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-070', 69),
    ('QUIMICA', 'FOSFATASA ALCATINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-071', 70),
    ('QUIMICA', 'FOSFORO', 'Sangre y derivados', 'Suero', 1, 'LABV2-072', 71),
    ('URIANALISIS', 'FOSFORO', 'Orina', 'Orina al azar', 1, 'LABV2-073', 72),
    ('HEMATOLOGIA', 'FROTIS DE SANGRE PERIFERICA', 'Sangre y derivados', 'Gota gruesa / frotis', 1, 'LABV2-074', 73),
    ('QUIMICA', 'GAMMA-GT', 'Sangre y derivados', 'Suero', 1, 'LABV2-075', 74),
    ('COPROLOGIA', 'GENERAL DE HECES', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-076', 75),
    ('URIANALISIS', 'GENERAL DE ORINA', 'Orina', 'Primera orina de la mañana', 1, 'LABV2-077', 76),
    ('QUIMICA', 'GLOBULINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-078', 77),
    ('QUIMICA', 'GLUCOSA', 'Sangre y derivados', 'Suero', 1, 'LABV2-079', 78),
    ('URIANALISIS', 'GLUCOSA', 'Orina', 'Orina al azar', 1, 'LABV2-080', 79),
    ('HEMATOLOGIA', 'GOTA GRUESA', 'Sangre y derivados', 'Gota gruesa / frotis', 1, 'LABV2-081', 80),
    ('MICROBIOLOGIA', 'HEMOCULTIVOS', 'Sangre y derivados', 'Hemocultivo', 2, 'LABV2-082', 81),
    ('PRUEBAS ESPECIALES', 'HEMOGLOBINA GLICOSILADA', 'Sangre y derivados', 'Suero', 1, 'LABV2-083', 82),
    ('HEMATOLOGIA', 'HEMOGRAMA COMPLETO', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-084', 83),
    ('QUIMICA', 'HIERRO', 'Sangre y derivados', 'Suero', 1, 'LABV2-085', 84),
    ('PRUEBAS ESPECIALES', 'HIV CUARTA GENERACIÓN', 'Sangre y derivados', 'Suero', 1, 'LABV2-086', 85),
    ('INMUNOLOGIA/SEROLOGIA', 'HIV-RAPIDO', 'Sangre y derivados', 'Suero', 1, 'LABV2-087', 86),
    ('HEMATOLOGIA', 'INDUCCIÓN DE DREPANOCITOS', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-088', 87),
    ('INMUNOLOGIA/SEROLOGIA', 'INFLUENZA Ag A/B/H1N1', 'Secreciones y exudados', 'Faríngeo / nasofaríngeo', 1, 'LABV2-089', 88),
    ('PRUEBAS ESPECIALES', 'INSULINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-090', 89),
    ('QUIMICA', 'LACTATO DESHIDROGENASA', 'Sangre y derivados', 'Suero', 1, 'LABV2-091', 90),
    ('INMUNOLOGIA/SEROLOGIA', 'LATEX-FACTOR REUMATOIDEO', 'Sangre y derivados', 'Suero', 1, 'LABV2-092', 91),
    ('QUIMICA', 'LIPASA', 'Sangre y derivados', 'Suero', 1, 'LABV2-093', 92),
    ('QUIMICA', 'MAGNESIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-094', 93),
    ('URIANALISIS', 'MAGNESIO', 'Orina', 'Orina al azar', 1, 'LABV2-095', 94),
    ('PRUEBAS ESPECIALES', 'MIOGLOBINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-096', 95),
    ('INMUNOLOGIA/SEROLOGIA', 'MONOTEST', 'Sangre y derivados', 'Suero', 1, 'LABV2-097', 96),
    ('QUIMICA', 'NITROGENO UREICO', 'Sangre y derivados', 'Suero', 1, 'LABV2-098', 97),
    ('URIANALISIS', 'NITROGENO UREICO', 'Orina', 'Orina al azar', 1, 'LABV2-099', 98),
    ('BIOLOGIA MOLECULAR', 'PANEL DE INFECCION', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-100', 99),
    ('BIOLOGIA MOLECULAR', 'PANEL DE SEPSIS', 'Sangre y derivados', 'Hemocultivo', 1, 'LABV2-101', 100),
    ('COPROLOGIA', 'PANEL GASTRICO VIRAL', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-102', 101),
    ('BIOLOGIA MOLECULAR', 'PANEL GASTROINTESTINAL', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-103', 102),
    ('INMUNOLOGIA/SEROLOGIA', 'PANEL ITS RAPIDO', 'Sangre y derivados', 'Suero', 1, 'LABV2-104', 103),
    ('BIOLOGIA MOLECULAR', 'PANEL MENINGITIS/ENCEFALITIS', 'Líquidos corporales', 'LCR', 1, 'LABV2-105', 104),
    ('INMUNOLOGIA/SEROLOGIA', 'PANEL RAPIDO ARBOVIRUS', 'Sangre y derivados', 'Suero', 1, 'LABV2-106', 105),
    ('URIANALISIS', 'PANEL RAPIDO DE DROGAS', 'Orina', 'Orina al azar', 1, 'LABV2-107', 106),
    ('BIOLOGIA MOLECULAR', 'PANEL RESPIRATOIRO', 'Secreciones y exudados', 'Faríngeo / nasofaríngeo', 1, 'LABV2-108', 107),
    ('INMUNOLOGIA/SEROLOGIA', 'PANEL RESPIRATORIO RAPIDO', 'Secreciones y exudados', 'Faríngeo / nasofaríngeo', 1, 'LABV2-109', 108),
    ('BIOLOGIA MOLECULAR', 'PANELPNEUMONIA', 'Tracto respiratorio', 'Aspirado / lavado bronquial', 1, 'LABV2-110', 109),
    ('PRUEBAS ESPECIALES', 'PCR-CARDIACA', 'Sangre y derivados', 'Suero', 1, 'LABV2-111', 110),
    ('COPROLOGIA', 'PH EN HECES', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-112', 111),
    ('QUIMICA', 'POTASIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-113', 112),
    ('URIANALISIS', 'POTASIO', 'Orina', 'Orina al azar', 1, 'LABV2-114', 113),
    ('PRUEBAS ESPECIALES', 'PRO-BNP', 'Sangre y derivados', 'Suero', 1, 'LABV2-115', 114),
    ('PRUEBAS ESPECIALES', 'PROCALCITONINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-116', 115),
    ('QUIMICA', 'PROTEINA C REACTIVA', 'Sangre y derivados', 'Suero', 1, 'LABV2-117', 116),
    ('QUIMICA', 'PROTEINAS TOTALES', 'Sangre y derivados', 'Suero', 1, 'LABV2-118', 117),
    ('URIANALISIS', 'PROTEINAS TOTALES', 'Orina', 'Orina al azar', 1, 'LABV2-119', 118),
    ('INMUNOLOGIA/SEROLOGIA', 'PRUEBA ASTO-LATEX', 'Sangre y derivados', 'Suero', 1, 'LABV2-120', 119),
    ('INMUNO-HEMATOLOGIA', 'PRUEBA CRUZADA', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-121', 120),
    ('INMUNOLOGIA/SEROLOGIA', 'PRUEBA DE EMBARAZO', 'Sangre y derivados', 'Suero', 1, 'LABV2-122', 121),
    ('URIANALISIS', 'PRUEBA DE EMBARAZO', 'Orina', 'Orina al azar', 1, 'LABV2-123', 122),
    ('INMUNO-HEMATOLOGIA', 'PRUEBA DU', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-124', 123),
    ('PRUEBAS ESPECIALES', 'PSA LIBRE', 'Sangre y derivados', 'Suero', 1, 'LABV2-125', 124),
    ('PRUEBAS ESPECIALES', 'PSA TOTAL', 'Sangre y derivados', 'Suero', 1, 'LABV2-126', 125),
    ('QUIMICA', 'RELACION ALBUMINA/GLOBULINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-127', 126),
    ('HEMATOLOGIA', 'RETICULOCITOS', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-128', 127),
    ('COPROLOGIA', 'ROTAVIRUS', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-129', 128),
    ('INMUNOLOGIA/SEROLOGIA', 'RPR-CARBON', 'Sangre y derivados', 'Suero', 1, 'LABV2-130', 129),
    ('COPROLOGIA', 'SANGRE OCULTA', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-131', 130),
    ('PRUEBAS ESPECIALES', 'SIFILIS CUARTA GENERACIÓN', 'Sangre y derivados', 'Suero', 1, 'LABV2-132', 131),
    ('INMUNOLOGIA/SEROLOGIA', 'SIFILIS-RAPIDO', 'Sangre y derivados', 'Suero', 1, 'LABV2-133', 132),
    ('QUIMICA', 'SODIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-134', 133),
    ('URIANALISIS', 'SODIO', 'Orina', 'Orina al azar', 1, 'LABV2-135', 134),
    ('COPROLOGIA', 'SUDAN III', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-136', 135),
    ('COPROLOGIA', 'SUSTANCIAS REDUCTORAS', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-137', 136),
    ('PRUEBAS ESPECIALES', 'T3 LIBRE', 'Sangre y derivados', 'Suero', 1, 'LABV2-138', 137),
    ('PRUEBAS ESPECIALES', 'T3 TOTAL', 'Sangre y derivados', 'Suero', 1, 'LABV2-139', 138),
    ('PRUEBAS ESPECIALES', 'T4 LIBRE', 'Sangre y derivados', 'Suero', 1, 'LABV2-140', 139),
    ('PRUEBAS ESPECIALES', 'T4 TOTAL', 'Sangre y derivados', 'Suero', 1, 'LABV2-141', 140),
    ('QUIMICA', 'TEST ''OSULLIVAN', 'Sangre y derivados', 'Suero', 1, 'LABV2-142', 141),
    ('QUIMICA', 'TGO', 'Sangre y derivados', 'Suero', 1, 'LABV2-143', 142),
    ('QUIMICA', 'TGP', 'Sangre y derivados', 'Suero', 1, 'LABV2-144', 143),
    ('COAGULACION', 'TIEMPO DE COAGULACIÓN', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-145', 144),
    ('COAGULACION', 'TIEMPO DE PROTROMBINA', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-146', 145),
    ('COAGULACION', 'TIEMPO DE SANGRAMIENTO', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-147', 146),
    ('COAGULACION', 'TIEMPO DE TROMBINA', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-148', 147),
    ('COAGULACION', 'TIEMPO DE TROMBOPLASTINA PARCIAL', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-149', 148),
    ('INMUNO-HEMATOLOGIA', 'TIPEO SANGUINEO', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-150', 149),
    ('QUIMICA', 'TRIGLICERIDO', 'Sangre y derivados', 'Suero', 1, 'LABV2-151', 150),
    ('PRUEBAS ESPECIALES', 'TROPONINA I', 'Sangre y derivados', 'Suero', 1, 'LABV2-152', 151),
    ('PRUEBAS ESPECIALES', 'TROPONINA T', 'Sangre y derivados', 'Suero', 1, 'LABV2-153', 152),
    ('PRUEBAS ESPECIALES', 'TSH', 'Sangre y derivados', 'Suero', 1, 'LABV2-154', 153),
    ('MICROBIOLOGIA', 'UROCULTIVO', 'Orina', 'Chorro medio (urocultivo)', 1, 'LABV2-155', 154),
    ('PRUEBAS ESPECIALES', 'VITAMINA B12', 'Sangre y derivados', 'Suero', 1, 'LABV2-156', 155),
    ('PRUEBAS ESPECIALES', 'VITAMINA D', 'Sangre y derivados', 'Suero', 1, 'LABV2-157', 156),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-158', 157),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-159', 158),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-160', 159),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-161', 160),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS  DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-162', 161),
    ('QUIMICA', 'CITOQUIMICO DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-163', 162),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-164', 163),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-165', 164),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-166', 165),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-167', 166),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-168', 167),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-169', 168),
    ('QUIMICA', 'pH DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-170', 169),
    ('QUIMICA', 'TRIGLICERIDOS DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-171', 170),
    ('MICROBIOLOGIA', 'ADENOSINA DESAMINASA (ADA)', 'Líquidos corporales', 'LCR', 1, 'LABV2-172', 171),
    ('BIOLOGIA MOLECULAR', 'GENEXPERT DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-173', 172),
    ('QUIMICA', 'LACTATO DESHIDROGENASA DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-174', 173),
    ('QUIMICA', 'PROTEINAS TOTALES DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-175', 174),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-176', 175),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-177', 176),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-178', 177),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-179', 178),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-180', 179),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LIQUIDO AMNIOTICO', 'Líquidos corporales', 'Amniótico', 1, 'LABV2-181', 180),
    ('QUIMICA', 'CITOQUIMICO DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-182', 181),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-183', 182),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-184', 183),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-185', 184),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-186', 185),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-187', 186),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-188', 187),
    ('QUIMICA', 'pH DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-189', 188),
    ('QUIMICA', 'LACTATO DESHIDROGENASA DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-190', 189),
    ('QUIMICA', 'PROTEINAS TOTALES DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-191', 190),
    ('BIOLOGIA MOLECULAR', 'GENEXPERT DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-192', 191),
    ('QUIMICA', 'CITOQUIMICO DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-193', 192),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-194', 193),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-195', 194),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-196', 195),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-197', 196),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-198', 197),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-199', 198),
    ('HEMATOLOGIA', 'RECUENTO CELULAR DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-200', 199),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-201', 200),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-202', 201),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-203', 202),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-204', 203),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-205', 204),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-206', 205),
    ('QUIMICA', 'ALBUMINA DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-207', 206),
    ('QUIMICA', 'CITOQUIMICODE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-208', 207),
    ('HEMATOLOGIA', 'RECUENTO CELULAR DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-209', 208),
    ('QUIMICA', 'CITOQUIMICO DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-210', 209),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-211', 210),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-212', 211),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-213', 212),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-214', 213),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-215', 214),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-216', 215),
    ('MICROBIOLOGIA', 'COLORACION GRAM DE ULCERA', 'Secreciones y exudados', 'Ulceras', 1, 'LABV2-217', 216),
    ('MICROBIOLOGIA', 'COLORACION GRAM DE ABSCESOS', 'Secreciones y exudados', 'Ulceras', 1, 'LABV2-218', 217)
)
INSERT INTO public."LabTest" (id, "organizationId", "panelId", code, name, specimen,
  "sampleTypeId", "sampleSubtypeId", "defaultQty", "displayOrder", active, "createdAt", "updatedAt")
SELECT gen_random_uuid(), p."organizationId", p.id, v.code, v.prueba, 'OTHER',
  st.id, ss.id, v.cant, v.ord, true, now(), now()
FROM v
JOIN public."LabPanel" p  ON p.area = 'LABORATORIO' AND upper(p.name) = upper(v.seccion) AND p."organizationId" IS NOT NULL
JOIN public."LabSampleType" st ON st.name = v.tipo AND st."organizationId" = p."organizationId"
LEFT JOIN public."LabSampleSubtype" ss ON ss."sampleTypeId" = st.id AND ss.name = v.subtipo
WHERE NOT EXISTS (
  SELECT 1 FROM public."LabTest" t
  WHERE t."panelId" = p.id AND t."organizationId" = p."organizationId"
    AND upper(t.name) = upper(v.prueba));

-- 4c. Desactivar pruebas del portafolio sembrado que ya no están en el JSON.
WITH v(seccion, prueba, tipo, subtipo, cant, code, ord) AS (VALUES
    ('PRUEBAS ESPECIALES', 'AC HEPATITIS C', 'Sangre y derivados', 'Suero', 1, 'LABV2-001', 0),
    ('QUIMICA', 'ACIDO URICO', 'Sangre y derivados', 'Suero', 1, 'LABV2-002', 1),
    ('URIANALISIS', 'ACIDO URICO', 'Orina', 'Orina al azar', 1, 'LABV2-003', 2),
    ('PRUEBAS ESPECIALES', 'AG AUSTRALIANO HEP B', 'Sangre y derivados', 'Suero', 1, 'LABV2-004', 3),
    ('COPROLOGIA', 'AG HELICOBACTER PYLORI', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-005', 4),
    ('INMUNO-HEMATOLOGIA', 'AGLUTININAS', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-006', 5),
    ('QUIMICA', 'ALBUMINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-007', 6),
    ('PRUEBAS ESPECIALES', 'ALFA FETO PROTEINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-008', 7),
    ('QUIMICA', 'AMILASA', 'Sangre y derivados', 'Suero', 1, 'LABV2-009', 8),
    ('URIANALISIS', 'AMILASA', 'Orina', 'Orina al azar', 1, 'LABV2-010', 9),
    ('QUIMICA', 'AMONIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-011', 10),
    ('COAGULACION', 'ANTICOAGULANTE LUPICO', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-012', 11),
    ('INMUNOLOGIA/SEROLOGIA', 'ANTICUERPOS ANTINUCLEARES', 'Sangre y derivados', 'Suero', 1, 'LABV2-013', 12),
    ('INMUNOLOGIA/SEROLOGIA', 'ANTICUERPOS HELICOBACTER PYLORI', 'Sangre y derivados', 'Suero', 1, 'LABV2-014', 13),
    ('INMUNO-HEMATOLOGIA', 'ANTICUERPOS IRREGULARES', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-015', 14),
    ('INMUNOLOGIA/SEROLOGIA', 'ANTIGENO COVID 19', 'Secreciones y exudados', 'Faríngeo / nasofaríngeo', 1, 'LABV2-016', 15),
    ('COPROLOGIA', 'ANTIGENO PARA SALMONELLA', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-017', 16),
    ('INMUNOLOGIA/SEROLOGIA', 'ANTIGENOS FEBRILES', 'Sangre y derivados', 'Suero', 1, 'LABV2-018', 17),
    ('COPROLOGIA', 'AZUL DE METILENO', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-019', 18),
    ('MICROBIOLOGIA', 'BACILOSCOPIA', 'Tracto respiratorio', 'Esputo', 1, 'LABV2-020', 19),
    ('QUIMICA', 'BILIRRUBINA DIRECTA', 'Sangre y derivados', 'Suero', 1, 'LABV2-021', 20),
    ('QUIMICA', 'BILIRRUBINA INDIRECTA', 'Sangre y derivados', 'Suero', 1, 'LABV2-022', 21),
    ('QUIMICA', 'BILIRRUBINA TOTAL', 'Sangre y derivados', 'Suero', 1, 'LABV2-023', 22),
    ('PRUEBAS ESPECIALES', 'CA 19-9', 'Sangre y derivados', 'Suero', 1, 'LABV2-024', 23),
    ('QUIMICA', 'CALCIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-025', 24),
    ('URIANALISIS', 'CALCIO', 'Orina', 'Orina al azar', 1, 'LABV2-026', 25),
    ('PRUEBAS ESPECIALES', 'ANTIGENO CARCINOEMBRIONARIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-027', 26),
    ('PRUEBAS ESPECIALES', 'CHAGAS', 'Sangre y derivados', 'Suero', 1, 'LABV2-028', 27),
    ('QUIMICA', 'CITOQUIMICO DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-029', 28),
    ('PRUEBAS ESPECIALES', 'CK-MB', 'Sangre y derivados', 'Suero', 1, 'LABV2-030', 29),
    ('QUIMICA', 'CPK-TOTAL', 'Sangre y derivados', 'Suero', 1, 'LABV2-031', 30),
    ('QUIMICA', 'CLORO', 'Sangre y derivados', 'Suero', 1, 'LABV2-032', 31),
    ('URIANALISIS', 'CLORO', 'Orina', 'Orina al azar', 1, 'LABV2-033', 32),
    ('COPROLOGIA', 'CLOSTRIDIUM-PRUEBA RAPIDA', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-034', 33),
    ('QUIMICA', 'COLESTEROL', 'Sangre y derivados', 'Suero', 1, 'LABV2-035', 34),
    ('QUIMICA', 'COLESTEROL HDL', 'Sangre y derivados', 'Suero', 1, 'LABV2-036', 35),
    ('QUIMICA', 'COLESTEROL LDL', 'Sangre y derivados', 'Suero', 1, 'LABV2-037', 36),
    ('COPROLOGIA', 'COLORACION DE COCCIDIOS', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-038', 37),
    ('HEMATOLOGIA', 'COLORACION DE WRIGHT', 'Sangre y derivados', 'Gota gruesa / frotis', 1, 'LABV2-039', 38),
    ('MICROBIOLOGIA', 'COLORACION GRAM', 'Secreciones y exudados', 'Heridas', 1, 'LABV2-040', 39),
    ('MICROBIOLOGIA', 'COLORACION ZIEHL-NEELSEN', 'Tracto respiratorio', 'Esputo', 1, 'LABV2-041', 40),
    ('INMUNOLOGIA/SEROLOGIA', 'COMBO DENGUE NS1/IgG/IgM', 'Sangre y derivados', 'Suero', 1, 'LABV2-042', 41),
    ('INMUNOLOGIA/SEROLOGIA', 'COMBO IgG/IgM HEPATITIS A', 'Sangre y derivados', 'Suero', 1, 'LABV2-043', 42),
    ('INMUNOLOGIA/SEROLOGIA', 'COMBO SARAMPION IgG/IgM', 'Sangre y derivados', 'Suero', 1, 'LABV2-044', 43),
    ('COPROLOGIA', 'CONCENTRADO DE HECES', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-045', 44),
    ('HEMATOLOGIA', 'CONCENTRADO DE STROUT', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-046', 45),
    ('HEMATOLOGIA', 'CONTEO DE EOSINOFILOS', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-047', 46),
    ('INMUNO-HEMATOLOGIA', 'COOMBS DIRECTO', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-048', 47),
    ('MICROBIOLOGIA', 'COPROCULTIVO', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-049', 48),
    ('PRUEBAS ESPECIALES', 'CORTISOL', 'Sangre y derivados', 'Suero', 1, 'LABV2-050', 49),
    ('QUIMICA', 'CREATININA', 'Sangre y derivados', 'Suero', 1, 'LABV2-051', 50),
    ('URIANALISIS', 'CREATININA', 'Orina', 'Orina al azar', 1, 'LABV2-052', 51),
    ('MICROBIOLOGIA', 'CULTIVO DE ESPUTO', 'Tracto respiratorio', 'Esputo', 1, 'LABV2-053', 52),
    ('MICROBIOLOGIA', 'CULTIVO DE HERIDA OPERATORIA', 'Secreciones y exudados', 'Heridas', 1, 'LABV2-054', 53),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-055', 54),
    ('MICROBIOLOGIA', 'CULTIVO DE ULCERA', 'Secreciones y exudados', 'Heridas', 1, 'LABV2-056', 55),
    ('MICROBIOLOGIA', 'CULTIVO ESPECIFICAR PROCEDENCIA', 'Otros', 'Ambientales / puntas de catéter', 1, 'LABV2-057', 56),
    ('MICROBIOLOGIA', 'CULTIVO VAGINAL', 'Secreciones y exudados', 'Uretral / vaginal / endocervical', 1, 'LABV2-058', 57),
    ('MICROBIOLOGIA', 'CULTIVOS FARINGEO', 'Secreciones y exudados', 'Faríngeo / nasofaríngeo', 1, 'LABV2-059', 58),
    ('QUIMICA', 'CURVA TOLERANCIA GLUCOSA', 'Sangre y derivados', 'Suero', 1, 'LABV2-060', 59),
    ('URIANALISIS', 'DEPURACION DE CREATININA', 'Orina', 'Orina de 24 horas', 1, 'LABV2-061', 60),
    ('URIANALISIS', 'DEPURACION DE PROTEINAS', 'Orina', 'Orina de 24 horas', 1, 'LABV2-062', 61),
    ('COAGULACION', 'DIMERO D', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-063', 62),
    ('URIANALISIS', 'DIMORFISMO ERITROCITARIO', 'Orina', 'Orina al azar', 1, 'LABV2-064', 63),
    ('MICROBIOLOGIA', 'DIRECTO KOH', 'Tejidos y médula', 'Raspados piel/uñas/pelo (micológico)', 1, 'LABV2-065', 64),
    ('MICROBIOLOGIA', 'DIRECTO TINTA CHINA DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-066', 65),
    ('HEMATOLOGIA', 'ERITROSEDIMENTACIÓN', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-067', 66),
    ('PRUEBAS ESPECIALES', 'FACTOR REUMATOIDEO', 'Sangre y derivados', 'Suero', 1, 'LABV2-068', 67),
    ('PRUEBAS ESPECIALES', 'FERRITINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-069', 68),
    ('COAGULACION', 'FIBRINOGENO', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-070', 69),
    ('QUIMICA', 'FOSFATASA ALCATINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-071', 70),
    ('QUIMICA', 'FOSFORO', 'Sangre y derivados', 'Suero', 1, 'LABV2-072', 71),
    ('URIANALISIS', 'FOSFORO', 'Orina', 'Orina al azar', 1, 'LABV2-073', 72),
    ('HEMATOLOGIA', 'FROTIS DE SANGRE PERIFERICA', 'Sangre y derivados', 'Gota gruesa / frotis', 1, 'LABV2-074', 73),
    ('QUIMICA', 'GAMMA-GT', 'Sangre y derivados', 'Suero', 1, 'LABV2-075', 74),
    ('COPROLOGIA', 'GENERAL DE HECES', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-076', 75),
    ('URIANALISIS', 'GENERAL DE ORINA', 'Orina', 'Primera orina de la mañana', 1, 'LABV2-077', 76),
    ('QUIMICA', 'GLOBULINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-078', 77),
    ('QUIMICA', 'GLUCOSA', 'Sangre y derivados', 'Suero', 1, 'LABV2-079', 78),
    ('URIANALISIS', 'GLUCOSA', 'Orina', 'Orina al azar', 1, 'LABV2-080', 79),
    ('HEMATOLOGIA', 'GOTA GRUESA', 'Sangre y derivados', 'Gota gruesa / frotis', 1, 'LABV2-081', 80),
    ('MICROBIOLOGIA', 'HEMOCULTIVOS', 'Sangre y derivados', 'Hemocultivo', 2, 'LABV2-082', 81),
    ('PRUEBAS ESPECIALES', 'HEMOGLOBINA GLICOSILADA', 'Sangre y derivados', 'Suero', 1, 'LABV2-083', 82),
    ('HEMATOLOGIA', 'HEMOGRAMA COMPLETO', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-084', 83),
    ('QUIMICA', 'HIERRO', 'Sangre y derivados', 'Suero', 1, 'LABV2-085', 84),
    ('PRUEBAS ESPECIALES', 'HIV CUARTA GENERACIÓN', 'Sangre y derivados', 'Suero', 1, 'LABV2-086', 85),
    ('INMUNOLOGIA/SEROLOGIA', 'HIV-RAPIDO', 'Sangre y derivados', 'Suero', 1, 'LABV2-087', 86),
    ('HEMATOLOGIA', 'INDUCCIÓN DE DREPANOCITOS', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-088', 87),
    ('INMUNOLOGIA/SEROLOGIA', 'INFLUENZA Ag A/B/H1N1', 'Secreciones y exudados', 'Faríngeo / nasofaríngeo', 1, 'LABV2-089', 88),
    ('PRUEBAS ESPECIALES', 'INSULINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-090', 89),
    ('QUIMICA', 'LACTATO DESHIDROGENASA', 'Sangre y derivados', 'Suero', 1, 'LABV2-091', 90),
    ('INMUNOLOGIA/SEROLOGIA', 'LATEX-FACTOR REUMATOIDEO', 'Sangre y derivados', 'Suero', 1, 'LABV2-092', 91),
    ('QUIMICA', 'LIPASA', 'Sangre y derivados', 'Suero', 1, 'LABV2-093', 92),
    ('QUIMICA', 'MAGNESIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-094', 93),
    ('URIANALISIS', 'MAGNESIO', 'Orina', 'Orina al azar', 1, 'LABV2-095', 94),
    ('PRUEBAS ESPECIALES', 'MIOGLOBINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-096', 95),
    ('INMUNOLOGIA/SEROLOGIA', 'MONOTEST', 'Sangre y derivados', 'Suero', 1, 'LABV2-097', 96),
    ('QUIMICA', 'NITROGENO UREICO', 'Sangre y derivados', 'Suero', 1, 'LABV2-098', 97),
    ('URIANALISIS', 'NITROGENO UREICO', 'Orina', 'Orina al azar', 1, 'LABV2-099', 98),
    ('BIOLOGIA MOLECULAR', 'PANEL DE INFECCION', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-100', 99),
    ('BIOLOGIA MOLECULAR', 'PANEL DE SEPSIS', 'Sangre y derivados', 'Hemocultivo', 1, 'LABV2-101', 100),
    ('COPROLOGIA', 'PANEL GASTRICO VIRAL', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-102', 101),
    ('BIOLOGIA MOLECULAR', 'PANEL GASTROINTESTINAL', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-103', 102),
    ('INMUNOLOGIA/SEROLOGIA', 'PANEL ITS RAPIDO', 'Sangre y derivados', 'Suero', 1, 'LABV2-104', 103),
    ('BIOLOGIA MOLECULAR', 'PANEL MENINGITIS/ENCEFALITIS', 'Líquidos corporales', 'LCR', 1, 'LABV2-105', 104),
    ('INMUNOLOGIA/SEROLOGIA', 'PANEL RAPIDO ARBOVIRUS', 'Sangre y derivados', 'Suero', 1, 'LABV2-106', 105),
    ('URIANALISIS', 'PANEL RAPIDO DE DROGAS', 'Orina', 'Orina al azar', 1, 'LABV2-107', 106),
    ('BIOLOGIA MOLECULAR', 'PANEL RESPIRATOIRO', 'Secreciones y exudados', 'Faríngeo / nasofaríngeo', 1, 'LABV2-108', 107),
    ('INMUNOLOGIA/SEROLOGIA', 'PANEL RESPIRATORIO RAPIDO', 'Secreciones y exudados', 'Faríngeo / nasofaríngeo', 1, 'LABV2-109', 108),
    ('BIOLOGIA MOLECULAR', 'PANELPNEUMONIA', 'Tracto respiratorio', 'Aspirado / lavado bronquial', 1, 'LABV2-110', 109),
    ('PRUEBAS ESPECIALES', 'PCR-CARDIACA', 'Sangre y derivados', 'Suero', 1, 'LABV2-111', 110),
    ('COPROLOGIA', 'PH EN HECES', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-112', 111),
    ('QUIMICA', 'POTASIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-113', 112),
    ('URIANALISIS', 'POTASIO', 'Orina', 'Orina al azar', 1, 'LABV2-114', 113),
    ('PRUEBAS ESPECIALES', 'PRO-BNP', 'Sangre y derivados', 'Suero', 1, 'LABV2-115', 114),
    ('PRUEBAS ESPECIALES', 'PROCALCITONINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-116', 115),
    ('QUIMICA', 'PROTEINA C REACTIVA', 'Sangre y derivados', 'Suero', 1, 'LABV2-117', 116),
    ('QUIMICA', 'PROTEINAS TOTALES', 'Sangre y derivados', 'Suero', 1, 'LABV2-118', 117),
    ('URIANALISIS', 'PROTEINAS TOTALES', 'Orina', 'Orina al azar', 1, 'LABV2-119', 118),
    ('INMUNOLOGIA/SEROLOGIA', 'PRUEBA ASTO-LATEX', 'Sangre y derivados', 'Suero', 1, 'LABV2-120', 119),
    ('INMUNO-HEMATOLOGIA', 'PRUEBA CRUZADA', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-121', 120),
    ('INMUNOLOGIA/SEROLOGIA', 'PRUEBA DE EMBARAZO', 'Sangre y derivados', 'Suero', 1, 'LABV2-122', 121),
    ('URIANALISIS', 'PRUEBA DE EMBARAZO', 'Orina', 'Orina al azar', 1, 'LABV2-123', 122),
    ('INMUNO-HEMATOLOGIA', 'PRUEBA DU', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-124', 123),
    ('PRUEBAS ESPECIALES', 'PSA LIBRE', 'Sangre y derivados', 'Suero', 1, 'LABV2-125', 124),
    ('PRUEBAS ESPECIALES', 'PSA TOTAL', 'Sangre y derivados', 'Suero', 1, 'LABV2-126', 125),
    ('QUIMICA', 'RELACION ALBUMINA/GLOBULINA', 'Sangre y derivados', 'Suero', 1, 'LABV2-127', 126),
    ('HEMATOLOGIA', 'RETICULOCITOS', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-128', 127),
    ('COPROLOGIA', 'ROTAVIRUS', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-129', 128),
    ('INMUNOLOGIA/SEROLOGIA', 'RPR-CARBON', 'Sangre y derivados', 'Suero', 1, 'LABV2-130', 129),
    ('COPROLOGIA', 'SANGRE OCULTA', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-131', 130),
    ('PRUEBAS ESPECIALES', 'SIFILIS CUARTA GENERACIÓN', 'Sangre y derivados', 'Suero', 1, 'LABV2-132', 131),
    ('INMUNOLOGIA/SEROLOGIA', 'SIFILIS-RAPIDO', 'Sangre y derivados', 'Suero', 1, 'LABV2-133', 132),
    ('QUIMICA', 'SODIO', 'Sangre y derivados', 'Suero', 1, 'LABV2-134', 133),
    ('URIANALISIS', 'SODIO', 'Orina', 'Orina al azar', 1, 'LABV2-135', 134),
    ('COPROLOGIA', 'SUDAN III', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-136', 135),
    ('COPROLOGIA', 'SUSTANCIAS REDUCTORAS', 'Heces', 'Heces frescas / preservante', 1, 'LABV2-137', 136),
    ('PRUEBAS ESPECIALES', 'T3 LIBRE', 'Sangre y derivados', 'Suero', 1, 'LABV2-138', 137),
    ('PRUEBAS ESPECIALES', 'T3 TOTAL', 'Sangre y derivados', 'Suero', 1, 'LABV2-139', 138),
    ('PRUEBAS ESPECIALES', 'T4 LIBRE', 'Sangre y derivados', 'Suero', 1, 'LABV2-140', 139),
    ('PRUEBAS ESPECIALES', 'T4 TOTAL', 'Sangre y derivados', 'Suero', 1, 'LABV2-141', 140),
    ('QUIMICA', 'TEST ''OSULLIVAN', 'Sangre y derivados', 'Suero', 1, 'LABV2-142', 141),
    ('QUIMICA', 'TGO', 'Sangre y derivados', 'Suero', 1, 'LABV2-143', 142),
    ('QUIMICA', 'TGP', 'Sangre y derivados', 'Suero', 1, 'LABV2-144', 143),
    ('COAGULACION', 'TIEMPO DE COAGULACIÓN', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-145', 144),
    ('COAGULACION', 'TIEMPO DE PROTROMBINA', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-146', 145),
    ('COAGULACION', 'TIEMPO DE SANGRAMIENTO', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-147', 146),
    ('COAGULACION', 'TIEMPO DE TROMBINA', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-148', 147),
    ('COAGULACION', 'TIEMPO DE TROMBOPLASTINA PARCIAL', 'Sangre y derivados', 'Plasma (citratado)', 1, 'LABV2-149', 148),
    ('INMUNO-HEMATOLOGIA', 'TIPEO SANGUINEO', 'Sangre y derivados', 'Sangre total (EDTA)', 1, 'LABV2-150', 149),
    ('QUIMICA', 'TRIGLICERIDO', 'Sangre y derivados', 'Suero', 1, 'LABV2-151', 150),
    ('PRUEBAS ESPECIALES', 'TROPONINA I', 'Sangre y derivados', 'Suero', 1, 'LABV2-152', 151),
    ('PRUEBAS ESPECIALES', 'TROPONINA T', 'Sangre y derivados', 'Suero', 1, 'LABV2-153', 152),
    ('PRUEBAS ESPECIALES', 'TSH', 'Sangre y derivados', 'Suero', 1, 'LABV2-154', 153),
    ('MICROBIOLOGIA', 'UROCULTIVO', 'Orina', 'Chorro medio (urocultivo)', 1, 'LABV2-155', 154),
    ('PRUEBAS ESPECIALES', 'VITAMINA B12', 'Sangre y derivados', 'Suero', 1, 'LABV2-156', 155),
    ('PRUEBAS ESPECIALES', 'VITAMINA D', 'Sangre y derivados', 'Suero', 1, 'LABV2-157', 156),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-158', 157),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-159', 158),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-160', 159),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-161', 160),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS  DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-162', 161),
    ('QUIMICA', 'CITOQUIMICO DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-163', 162),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-164', 163),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-165', 164),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-166', 165),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-167', 166),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-168', 167),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-169', 168),
    ('QUIMICA', 'pH DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-170', 169),
    ('QUIMICA', 'TRIGLICERIDOS DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-171', 170),
    ('MICROBIOLOGIA', 'ADENOSINA DESAMINASA (ADA)', 'Líquidos corporales', 'LCR', 1, 'LABV2-172', 171),
    ('BIOLOGIA MOLECULAR', 'GENEXPERT DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-173', 172),
    ('QUIMICA', 'LACTATO DESHIDROGENASA DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-174', 173),
    ('QUIMICA', 'PROTEINAS TOTALES DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-175', 174),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LCR', 'Líquidos corporales', 'LCR', 1, 'LABV2-176', 175),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LIQUIDO PLEURAL', 'Líquidos corporales', 'Pleural', 1, 'LABV2-177', 176),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-178', 177),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-179', 178),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-180', 179),
    ('CITOPATOLOGIA', 'CITOLOGICO DE LIQUIDO AMNIOTICO', 'Líquidos corporales', 'Amniótico', 1, 'LABV2-181', 180),
    ('QUIMICA', 'CITOQUIMICO DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-182', 181),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-183', 182),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-184', 183),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-185', 184),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-186', 185),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-187', 186),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-188', 187),
    ('QUIMICA', 'pH DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-189', 188),
    ('QUIMICA', 'LACTATO DESHIDROGENASA DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-190', 189),
    ('QUIMICA', 'PROTEINAS TOTALES DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-191', 190),
    ('BIOLOGIA MOLECULAR', 'GENEXPERT DE LIQUIDO PERICARDICO', 'Líquidos corporales', 'Pericárdico', 1, 'LABV2-192', 191),
    ('QUIMICA', 'CITOQUIMICO DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-193', 192),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-194', 193),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-195', 194),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-196', 195),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-197', 196),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-198', 197),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-199', 198),
    ('HEMATOLOGIA', 'RECUENTO CELULAR DE LIQUIDO PERITONEAL', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-200', 199),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-201', 200),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-202', 201),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-203', 202),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-204', 203),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-205', 204),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-206', 205),
    ('QUIMICA', 'ALBUMINA DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-207', 206),
    ('QUIMICA', 'CITOQUIMICODE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-208', 207),
    ('HEMATOLOGIA', 'RECUENTO CELULAR DE LIQUIDO ASCITICO', 'Líquidos corporales', 'Peritoneal', 1, 'LABV2-209', 208),
    ('QUIMICA', 'CITOQUIMICO DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-210', 209),
    ('MICROBIOLOGIA', 'DIRECTO BAAR DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-211', 210),
    ('MICROBIOLOGIA', 'DIRECTO NO BAAR DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-212', 211),
    ('MICROBIOLOGIA', 'DIRECTO HONGOS DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-213', 212),
    ('MICROBIOLOGIA', 'CULTIVO BAAR DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-214', 213),
    ('MICROBIOLOGIA', 'CULTIVO NO BAAR DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-215', 214),
    ('MICROBIOLOGIA', 'CULTIVO HONGOS DE LIQUIDO SINOVIAL', 'Líquidos corporales', 'Sinovial (articular)', 1, 'LABV2-216', 215),
    ('MICROBIOLOGIA', 'COLORACION GRAM DE ULCERA', 'Secreciones y exudados', 'Ulceras', 1, 'LABV2-217', 216),
    ('MICROBIOLOGIA', 'COLORACION GRAM DE ABSCESOS', 'Secreciones y exudados', 'Ulceras', 1, 'LABV2-218', 217)
)
UPDATE public."LabTest" t SET active = false, "updatedAt" = now()
FROM public."LabPanel" p
WHERE t."panelId" = p.id AND p.area = 'LABORATORIO'
  AND t."organizationId" IS NOT NULL
  AND (t.code LIKE 'PORT-%' OR t.code LIKE 'LABV2-%')
  AND t.active = true
  AND NOT EXISTS (
    SELECT 1 FROM v
    WHERE upper(v.seccion) = upper(p.name) AND upper(v.prueba) = upper(t.name));
