/**
 * Catálogo de KPIs del Dashboard Ejecutivo Multiorganizacional.
 *
 * Fuente: docs/kpi/catalogo_his_multiorganizacional.md (40+ KPIs en 7 categorías).
 *
 * Cada KPI tiene metadata completa para que el componente <KpiCard /> pueda
 * renderizarlo de forma uniforme: descripción aclaratoria, fórmula, meta,
 * umbral, frecuencia, fuente, responsable.
 *
 * `dataSource`:
 *   - "real":      query en BD productiva implementada.
 *   - "mock":      valores demo (sin fuente todavía — placeholder).
 *   - "pending":   integración externa pendiente (APM, finance, ITSM, NPS).
 *
 * El dashboard renderiza TODOS — los "mock" y "pending" muestran badge
 * "Pendiente integración" para que el usuario entienda el estado real.
 */

export type Categoria =
  | "tecnicos"
  | "adopcion"
  | "calidad_datos"
  | "asistenciales"
  | "financieros"
  | "seguridad"
  | "gobierno";

export type Clasificacion = "operativo" | "estrategico" | "operativo_estrategico";
export type Frecuencia    = "tiempo_real" | "operativo" | "estrategico";
export type DataSource    = "real" | "mock" | "pending";

export interface KpiDefinition {
  /** ID estable (snake_case). Usado por el router y URLs/exports. */
  id: string;
  /** Categoría a la que pertenece. */
  categoria: Categoria;
  /** Título corto para card y exportes. */
  titulo: string;
  /** Descripción aclaratoria — qué mide y por qué importa (≤ 200 chars). */
  descripcion: string;
  /** Fórmula textual (legible para humanos, no SQL). */
  formula: string;
  /** Unidad (%, segundos, días, eventos por 1000 pacientes, etc.). */
  unidad: string;
  /** Meta institucional (texto, p.ej. "≥ 99.5% mensual"). */
  meta: string;
  /** Umbral que dispara alerta (texto, opcional). */
  umbralCritico?: string;
  frecuencia: Frecuencia;
  fuente: string;
  visualizacion: string;
  clasificacion: Clasificacion;
  responsable: string;
  dataSource: DataSource;
  /** Si true, este KPI es parte de la Capa 1 ejecutiva (10-12 estratégicos). */
  capaEjecutiva: boolean;
}

export const KPI_CATALOG: ReadonlyArray<KpiDefinition> = [
  // -----------------------------------------------------------------------
  // 1. TÉCNICOS Y OPERATIVOS
  // -----------------------------------------------------------------------
  {
    id: "tec_uptime",
    categoria: "tecnicos",
    titulo: "Disponibilidad del Sistema (Uptime)",
    descripcion: "Porcentaje de tiempo en que el HIS está operativo y accesible dentro de la ventana de servicio comprometida.",
    formula: "(Tiempo total operativo / Tiempo total medido) × 100",
    unidad: "%",
    meta: "≥ 99.5% mensual por organización",
    umbralCritico: "< 98% dispara alerta a TI",
    frecuencia: "tiempo_real",
    fuente: "Sistema de monitoreo de infraestructura (Vercel/health checks)",
    visualizacion: "Semáforo por organización + tendencia 30 días",
    clasificacion: "operativo_estrategico",
    responsable: "Dirección de TI / Proveedor del HIS",
    dataSource: "real",
    capaEjecutiva: true,
  },
  {
    id: "tec_response_time",
    categoria: "tecnicos",
    titulo: "Tiempo de Respuesta Transacciones Críticas",
    descripcion: "Tiempo promedio de las transacciones más utilizadas: consulta de expediente, signos vitales, prescripción, facturación.",
    formula: "Σ tiempo de respuesta / total de transacciones",
    unidad: "segundos",
    meta: "≤ 2s consulta · ≤ 4s transaccional",
    umbralCritico: "> 6s sostenido 5 min",
    frecuencia: "tiempo_real",
    fuente: "Logs aplicación + APM",
    visualizacion: "Líneas p50/p90/p99",
    clasificacion: "operativo",
    responsable: "Dirección de TI",
    dataSource: "pending",
    capaEjecutiva: false,
  },
  {
    id: "tec_mtbf_mttr",
    categoria: "tecnicos",
    titulo: "MTBF / MTTR",
    descripcion: "Tiempo medio entre fallas y de recuperación; mide la madurez operativa del HIS.",
    formula: "MTBF: tiempo operativo / nº fallas · MTTR: Σ tiempo recuperación / nº incidentes",
    unidad: "horas",
    meta: "MTBF ≥ 720h · MTTR ≤ 1h crítico",
    frecuencia: "operativo",
    fuente: "ITSM",
    visualizacion: "Tarjetas con comparativo mes a mes",
    clasificacion: "estrategico",
    responsable: "Dirección de TI",
    dataSource: "real",
    capaEjecutiva: false,
  },
  {
    id: "tec_sla_compliance",
    categoria: "tecnicos",
    titulo: "Cumplimiento SLA por Proveedor",
    descripcion: "Cumplimiento de acuerdos de nivel de servicio segmentado por proveedor y módulo (clínico, finanzas, lab, farmacia).",
    formula: "(Incidentes resueltos dentro SLA / total incidentes) × 100",
    unidad: "%",
    meta: "≥ 95% mensual",
    frecuencia: "operativo",
    fuente: "ITSM con severidad",
    visualizacion: "Barras apiladas por proveedor",
    clasificacion: "estrategico",
    responsable: "Dirección de TI / Gestión de proveedores",
    dataSource: "pending",
    capaEjecutiva: true,
  },
  {
    id: "tec_capacity_usage",
    categoria: "tecnicos",
    titulo: "Uso de Capacidad por Organización",
    descripcion: "Consumo de CPU, memoria, almacenamiento, ancho de banda atribuible a cada organización.",
    formula: "Consumo del recurso por org / capacidad total × 100",
    unidad: "%",
    meta: "< 75% sostenido · > 85% planear capacidad",
    frecuencia: "tiempo_real",
    fuente: "Plataforma monitoreo infra",
    visualizacion: "Heatmap org × recurso",
    clasificacion: "estrategico",
    responsable: "Dirección de TI / Finanzas",
    dataSource: "real",
    capaEjecutiva: false,
  },

  // -----------------------------------------------------------------------
  // 2. ADOPCIÓN Y USO
  // -----------------------------------------------------------------------
  {
    id: "adp_usuarios_activos",
    categoria: "adopcion",
    titulo: "Porcentaje de Usuarios Activos",
    descripcion: "Proporción de usuarios licenciados que han ejecutado al menos una transacción en el periodo.",
    formula: "(Usuarios con tx en periodo / total licenciados) × 100",
    unidad: "%",
    meta: "≥ 85% semanal por organización",
    frecuencia: "operativo",
    fuente: "Logs de autenticación HIS",
    visualizacion: "Barras horizontales comparativas",
    clasificacion: "operativo_estrategico",
    responsable: "Dirección de cada organización",
    dataSource: "real",
    capaEjecutiva: true,
  },
  {
    id: "adp_tx_por_usuario",
    categoria: "adopcion",
    titulo: "Transacciones por Usuario",
    descripcion: "Intensidad real de uso del HIS más allá del simple acceso.",
    formula: "Total transacciones / nº usuarios activos",
    unidad: "tx/usuario",
    meta: "Definida por perfil",
    frecuencia: "operativo",
    fuente: "Logs transaccionales",
    visualizacion: "Barras comparativas org",
    clasificacion: "operativo",
    responsable: "Dirección de operaciones",
    dataSource: "real",
    capaEjecutiva: false,
  },
  {
    id: "adp_modulos_clave",
    categoria: "adopcion",
    titulo: "Adopción de Módulos Clave",
    descripcion: "Uso real de módulos estratégicos: prescripción electrónica, expediente, laboratorio, farmacia, imágenes.",
    formula: "(Procesos ejecutados / potencialmente ejecutables) × 100",
    unidad: "%",
    meta: "≥ 90% por módulo crítico",
    frecuencia: "estrategico",
    fuente: "Reportes uso por módulo",
    visualizacion: "Matriz calor módulos × orgs",
    clasificacion: "estrategico",
    responsable: "Dirección médica / TI",
    dataSource: "real",
    capaEjecutiva: true,
  },
  {
    id: "adp_procesos_digitalizados",
    categoria: "adopcion",
    titulo: "Procesos Digitalizados",
    descripcion: "Proporción de procesos clínicos y administrativos ejecutados íntegramente en el HIS vs papel/sistemas paralelos.",
    formula: "(Procesos en HIS / total procesos) × 100",
    unidad: "%",
    meta: "≥ 95%",
    frecuencia: "estrategico",
    fuente: "Auditorías de procesos",
    visualizacion: "KPI + tendencia trimestral",
    clasificacion: "estrategico",
    responsable: "Comité directivo",
    dataSource: "real",
    capaEjecutiva: false,
  },

  // -----------------------------------------------------------------------
  // 3. CALIDAD DE DATOS E INTEROPERABILIDAD
  // -----------------------------------------------------------------------
  {
    id: "dat_completos",
    categoria: "calidad_datos",
    titulo: "Registros Completos en Campos Críticos",
    descripcion: "Proporción de registros con todos los campos críticos completos según reglas de negocio.",
    formula: "(Registros completos / total registros) × 100",
    unidad: "%",
    meta: "≥ 98%",
    frecuencia: "operativo",
    fuente: "Reglas de validación sobre BD HIS",
    visualizacion: "Tarjeta + desglose org",
    clasificacion: "operativo_estrategico",
    responsable: "Dirección médica / TI",
    dataSource: "real",
    capaEjecutiva: false,
  },
  {
    id: "dat_duplicidad_mpi",
    categoria: "calidad_datos",
    titulo: "Duplicidad de Pacientes (MPI)",
    descripcion: "Porcentaje de registros de pacientes detectados como duplicados en el Master Patient Index unificado.",
    formula: "(Registros duplicados / total pacientes) × 100",
    unidad: "%",
    meta: "≤ 1%",
    umbralCritico: "> 3% dispara auditoría MPI",
    frecuencia: "operativo",
    fuente: "Algoritmo matching MPI",
    visualizacion: "KPI + tendencia + desglose org",
    clasificacion: "estrategico",
    responsable: "Dirección médica / Gobierno de datos",
    dataSource: "real",
    capaEjecutiva: true,
  },
  {
    id: "dat_codificacion",
    categoria: "calidad_datos",
    titulo: "Codificación Correcta",
    descripcion: "Proporción de diagnósticos y procedimientos correctamente codificados (CIE-10, CPT).",
    formula: "(Registros validados / total codificados) × 100",
    unidad: "%",
    meta: "≥ 97%",
    frecuencia: "operativo",
    fuente: "Auditorías codificación",
    visualizacion: "Barras org × catálogo",
    clasificacion: "estrategico",
    responsable: "Dirección médica",
    dataSource: "real",
    capaEjecutiva: false,
  },
  {
    id: "dat_hl7_fhir",
    categoria: "calidad_datos",
    titulo: "Intercambios HL7 / FHIR",
    descripcion: "Cantidad de mensajes intercambiados entre sistemas y orgs, con tasa de éxito.",
    formula: "(Mensajes exitosos / enviados) × 100",
    unidad: "% y msg/hora",
    meta: "≥ 99.5% éxito",
    frecuencia: "tiempo_real",
    fuente: "Motor de integración HL7/FHIR",
    visualizacion: "Línea + log errores recientes",
    clasificacion: "operativo",
    responsable: "Dirección de TI",
    dataSource: "real",
    capaEjecutiva: false,
  },
  {
    id: "dat_propagacion_maestros",
    categoria: "calidad_datos",
    titulo: "Propagación Cambios Maestros",
    descripcion: "Tiempo que tarda un cambio en catálogos maestros (tarifarios, protocolos, medicamentos) en aplicarse en todas las orgs.",
    formula: "Tiempo publicación → aplicación última org",
    unidad: "horas",
    meta: "≤ 24 horas",
    frecuencia: "operativo",
    fuente: "Logs despliegue y sincronización",
    visualizacion: "Tabla últimos 10 cambios",
    clasificacion: "estrategico",
    responsable: "Dirección TI / Gobierno datos",
    dataSource: "real",
    capaEjecutiva: false,
  },

  // -----------------------------------------------------------------------
  // 4. ASISTENCIALES
  // -----------------------------------------------------------------------
  {
    id: "asi_estancia",
    categoria: "asistenciales",
    titulo: "Promedio de Estancia Hospitalaria",
    descripcion: "Número promedio de días que un paciente permanece hospitalizado desde ingreso hasta egreso.",
    formula: "Σ días estancia / nº egresos",
    unidad: "días",
    meta: "Definida por servicio/patología",
    frecuencia: "estrategico",
    fuente: "Módulo admisión-egreso",
    visualizacion: "Boxplot servicio × org",
    clasificacion: "estrategico",
    responsable: "Dirección médica",
    dataSource: "real",
    capaEjecutiva: false,
  },
  {
    id: "asi_ocupacion_camas",
    categoria: "asistenciales",
    titulo: "Tasa de Ocupación de Camas",
    descripcion: "Porcentaje de camas ocupadas respecto a la capacidad instalada disponible.",
    formula: "(Camas ocupadas / disponibles) × 100",
    unidad: "%",
    meta: "75% - 85% (rango óptimo)",
    frecuencia: "tiempo_real",
    fuente: "Módulo gestión de camas",
    visualizacion: "Heatmap org × servicio",
    clasificacion: "operativo_estrategico",
    responsable: "Dirección médica / operaciones",
    dataSource: "real",
    capaEjecutiva: true,
  },
  {
    id: "asi_reingreso_30d",
    categoria: "asistenciales",
    titulo: "Reingreso a 30 Días",
    descripcion: "Porcentaje de pacientes que reingresan dentro de los 30 días posteriores al alta por causa relacionada.",
    formula: "(Reingresos ≤30d / total egresos) × 100",
    unidad: "%",
    meta: "≤ 5%",
    frecuencia: "estrategico",
    fuente: "Módulo admisión-egreso",
    visualizacion: "KPI + benchmark entre orgs",
    clasificacion: "estrategico",
    responsable: "Dirección médica",
    dataSource: "real",
    capaEjecutiva: true,
  },
  {
    id: "asi_espera_urgencias",
    categoria: "asistenciales",
    titulo: "Tiempos de Espera (Urgencias / Consulta)",
    descripcion: "Tiempo promedio entre registro/solicitud y atención médica efectiva.",
    formula: "Σ tiempo espera / nº pacientes",
    unidad: "minutos",
    meta: "Urgencias ≤ 15 min triage · Consulta ≤ 20 min",
    frecuencia: "tiempo_real",
    fuente: "Módulos urgencias / consulta",
    visualizacion: "Línea de tiempo + percentiles",
    clasificacion: "operativo",
    responsable: "Dirección médica",
    dataSource: "real",
    capaEjecutiva: false,
  },
  {
    id: "asi_infecciones_nosocomiales",
    categoria: "asistenciales",
    titulo: "Infecciones Nosocomiales",
    descripcion: "Proporción de pacientes con infecciones asociadas a la atención sanitaria durante hospitalización.",
    formula: "(Pacientes con IAAS / total hospitalizados) × 100",
    unidad: "%",
    meta: "≤ 3%",
    frecuencia: "estrategico",
    fuente: "Módulo epidemiología y vigilancia",
    visualizacion: "Tendencia mensual + alertas brote",
    clasificacion: "estrategico",
    responsable: "Comité infecciones / Dirección médica",
    dataSource: "mock",
    capaEjecutiva: false,
  },
  {
    id: "asi_adherencia_protocolos",
    categoria: "asistenciales",
    titulo: "Adherencia a Protocolos Clínicos",
    descripcion: "Porcentaje de atenciones que siguen protocolos clínicos establecidos.",
    formula: "(Atenciones con protocolo / elegibles) × 100",
    unidad: "%",
    meta: "≥ 90%",
    frecuencia: "estrategico",
    fuente: "Reglas clínicas HIS + auditorías",
    visualizacion: "Barras por protocolo × org",
    clasificacion: "estrategico",
    responsable: "Dirección médica",
    dataSource: "mock",
    capaEjecutiva: false,
  },
  {
    id: "asi_eventos_adversos",
    categoria: "asistenciales",
    titulo: "Eventos Adversos por 1,000 Pacientes",
    descripcion: "Eventos adversos reportados (errores medicación, caídas, úlceras) por cada 1,000 pacientes atendidos.",
    formula: "(Eventos × 1,000) / total pacientes",
    unidad: "eventos/1000 pacientes",
    meta: "Tendencia descendente",
    frecuencia: "operativo",
    fuente: "Módulo seguridad del paciente",
    visualizacion: "Tabla + tendencia + alerta umbral",
    clasificacion: "estrategico",
    responsable: "Comité seguridad del paciente",
    dataSource: "real",
    capaEjecutiva: true,
  },

  // -----------------------------------------------------------------------
  // 5. FINANCIEROS Y CICLO DE INGRESOS
  // -----------------------------------------------------------------------
  {
    id: "fin_costo_egreso",
    categoria: "financieros",
    titulo: "Costo por Egreso",
    descripcion: "Costo promedio asociado a la atención completa de un paciente o egreso hospitalario.",
    formula: "Costos totales / nº egresos",
    unidad: "USD",
    meta: "Definida por tipo paciente/servicio",
    frecuencia: "estrategico",
    fuente: "Módulo financiero",
    visualizacion: "Comparativo org × tipo paciente",
    clasificacion: "estrategico",
    responsable: "Dirección financiera",
    dataSource: "real",
    capaEjecutiva: false,
  },
  {
    id: "fin_dso",
    categoria: "financieros",
    titulo: "Días en Cuentas por Cobrar (DSO)",
    descripcion: "Número promedio de días que la organización tarda en cobrar sus cuentas tras facturación.",
    formula: "(CxC / ingresos del periodo) × días periodo",
    unidad: "días",
    meta: "≤ 45 días",
    frecuencia: "operativo",
    fuente: "Módulo cuentas por cobrar",
    visualizacion: "KPI + tendencia",
    clasificacion: "estrategico",
    responsable: "Dirección financiera",
    dataSource: "real",
    capaEjecutiva: true,
  },
  {
    id: "fin_rechazo_reclamaciones",
    categoria: "financieros",
    titulo: "Rechazo de Reclamaciones",
    descripcion: "Porcentaje de reclamaciones a aseguradoras rechazadas total o parcialmente en primera instancia.",
    formula: "(Rechazadas / total enviadas) × 100",
    unidad: "%",
    meta: "≤ 5%",
    frecuencia: "operativo",
    fuente: "Módulo facturación / aseguradoras",
    visualizacion: "Tabla con motivos principales",
    clasificacion: "operativo_estrategico",
    responsable: "Dirección financiera",
    dataSource: "real",
    capaEjecutiva: true,
  },
  {
    id: "fin_factura_electronica",
    categoria: "financieros",
    titulo: "Facturación Electrónica Exitosa",
    descripcion: "Proporción de facturas validadas y aceptadas en primera transmisión por autoridad fiscal o aseguradoras.",
    formula: "(Aceptadas 1ª transmisión / emitidas) × 100",
    unidad: "%",
    meta: "≥ 98%",
    frecuencia: "tiempo_real",
    fuente: "Módulo facturación electrónica",
    visualizacion: "KPI + log errores",
    clasificacion: "operativo",
    responsable: "Dirección financiera",
    dataSource: "real",
    capaEjecutiva: false,
  },
  {
    id: "fin_margen",
    categoria: "financieros",
    titulo: "Margen por Servicio / Organización",
    descripcion: "Diferencia porcentual entre ingresos y costos, segmentada por servicio clínico y por organización.",
    formula: "((Ingresos − Costos) / Ingresos) × 100",
    unidad: "%",
    meta: "Definida por servicio",
    frecuencia: "estrategico",
    fuente: "Módulo financiero",
    visualizacion: "Heatmap servicio × org",
    clasificacion: "estrategico",
    responsable: "Dirección financiera",
    dataSource: "real",
    capaEjecutiva: false,
  },
  {
    id: "fin_costo_his",
    categoria: "financieros",
    titulo: "Costo del HIS por Usuario / Transacción",
    descripcion: "Costo total del HIS dividido entre usuarios activos o transacciones procesadas.",
    formula: "Costo total HIS / (usuarios o tx)",
    unidad: "USD",
    meta: "Tendencia descendente trimestral",
    frecuencia: "estrategico",
    fuente: "Módulo financiero + uso",
    visualizacion: "Tarjeta + comparativo trimestral",
    clasificacion: "estrategico",
    responsable: "Dirección financiera / TI",
    dataSource: "pending",
    capaEjecutiva: false,
  },

  // -----------------------------------------------------------------------
  // 6. SEGURIDAD Y CUMPLIMIENTO
  // -----------------------------------------------------------------------
  {
    id: "seg_incidentes",
    categoria: "seguridad",
    titulo: "Incidentes de Seguridad",
    descripcion: "Total de incidentes de seguridad detectados y registrados por organización y severidad.",
    formula: "Conteo del periodo",
    unidad: "incidentes",
    meta: "Tendencia descendente · cero críticos",
    frecuencia: "operativo",
    fuente: "SIEM + gestor incidentes",
    visualizacion: "Tabla severidad × org",
    clasificacion: "operativo_estrategico",
    responsable: "Dirección de seguridad",
    dataSource: "real",
    capaEjecutiva: true,
  },
  {
    id: "seg_accesos_no_autorizados",
    categoria: "seguridad",
    titulo: "Accesos No Autorizados Detectados",
    descripcion: "Intentos de acceso no autorizado a expedientes o módulos restringidos detectados por auditoría.",
    formula: "Conteo de eventos auditados",
    unidad: "eventos",
    meta: "Investigación obligatoria de todo evento",
    frecuencia: "tiempo_real",
    fuente: "Logs de auditoría HIS",
    visualizacion: "Alerta + log detallado",
    clasificacion: "operativo",
    responsable: "Dirección de seguridad",
    dataSource: "real",
    capaEjecutiva: false,
  },
  {
    id: "seg_mfa",
    categoria: "seguridad",
    titulo: "Usuarios con MFA Activa",
    descripcion: "Proporción de usuarios HIS con segundo factor de autenticación activo (especial enfocque en privilegiados).",
    formula: "(Usuarios con MFA / total) × 100",
    unidad: "%",
    meta: "100% privilegiados · ≥ 95% general",
    frecuencia: "operativo",
    fuente: "Plataforma de identidad",
    visualizacion: "KPI + desglose rol/org",
    clasificacion: "estrategico",
    responsable: "Dirección de seguridad",
    dataSource: "real",
    capaEjecutiva: true,
  },
  {
    id: "seg_auditorias",
    categoria: "seguridad",
    titulo: "Cumplimiento Auditorías Regulatorias",
    descripcion: "Porcentaje de hallazgos cerrados a tiempo (HIPAA, ISO 27001, regulaciones locales).",
    formula: "(Cerrados en plazo / total hallazgos) × 100",
    unidad: "%",
    meta: "≥ 95%",
    frecuencia: "estrategico",
    fuente: "Sistema gestión de cumplimiento",
    visualizacion: "Tabla hallazgos × categoría",
    clasificacion: "estrategico",
    responsable: "Dirección de cumplimiento",
    dataSource: "mock",
    capaEjecutiva: false,
  },
  {
    id: "seg_parches",
    categoria: "seguridad",
    titulo: "Antigüedad Parches Críticos",
    descripcion: "Tiempo promedio entre liberación de parche de seguridad crítico y aplicación en componentes HIS.",
    formula: "Σ días sin aplicar / nº parches pendientes",
    unidad: "días",
    meta: "≤ 7 días",
    frecuencia: "operativo",
    fuente: "Plataforma gestión de vulnerabilidades",
    visualizacion: "Lista parches pendientes",
    clasificacion: "operativo_estrategico",
    responsable: "Dirección seguridad / TI",
    dataSource: "real",
    capaEjecutiva: false,
  },

  // -----------------------------------------------------------------------
  // 7. GOBIERNO Y SOPORTE
  // -----------------------------------------------------------------------
  {
    id: "gob_tickets_resolucion",
    categoria: "gobierno",
    titulo: "Tiempo de Resolución de Tickets",
    descripcion: "Tiempo promedio que soporte tarda en resolver un ticket, segmentado por severidad.",
    formula: "Σ tiempo resolución / nº tickets resueltos",
    unidad: "horas",
    meta: "S1≤4h · S2≤12h · S3≤48h",
    frecuencia: "operativo",
    fuente: "Plataforma ITSM",
    visualizacion: "Barras severidad × org",
    clasificacion: "operativo_estrategico",
    responsable: "Dirección TI / Soporte",
    dataSource: "real",
    capaEjecutiva: false,
  },
  {
    id: "gob_satisfaccion",
    categoria: "gobierno",
    titulo: "Satisfacción del Usuario (NPS/CSAT)",
    descripcion: "Nivel de satisfacción de usuarios medido por encuestas NPS o CSAT.",
    formula: "NPS: %Promotores − %Detractores · CSAT: (satisfechas / total) × 100",
    unidad: "NPS (-100 a +100) · CSAT %",
    meta: "NPS ≥ +30 · CSAT ≥ 85%",
    frecuencia: "estrategico",
    fuente: "Plataforma de encuestas",
    visualizacion: "Tarjeta + tendencia",
    clasificacion: "estrategico",
    responsable: "Comité directivo",
    dataSource: "pending",
    capaEjecutiva: true,
  },
  {
    id: "gob_backlog",
    categoria: "gobierno",
    titulo: "Cumplimiento Backlog de Mejoras",
    descripcion: "Porcentaje de mejoras/desarrollos entregados a cada organización dentro del plazo acordado.",
    formula: "(Entregadas en plazo / comprometidas) × 100",
    unidad: "%",
    meta: "≥ 90%",
    frecuencia: "estrategico",
    fuente: "Plataforma gestión proyectos",
    visualizacion: "Barras org × trimestre",
    clasificacion: "estrategico",
    responsable: "Dirección TI / Gobierno HIS",
    dataSource: "real",
    capaEjecutiva: false,
  },
  {
    id: "gob_cambios_estandar",
    categoria: "gobierno",
    titulo: "Cambios Estandarizados vs Personalizados",
    descripcion: "Relación entre cambios desplegados a todas las orgs (estandar) vs específicos para una sola (personalizados).",
    formula: "(Estandarizados / total cambios) × 100",
    unidad: "%",
    meta: "≥ 80% estandarizados",
    frecuencia: "estrategico",
    fuente: "Plataforma gestión cambios",
    visualizacion: "KPI + tendencia",
    clasificacion: "estrategico",
    responsable: "Comité de gobernanza HIS",
    dataSource: "pending",
    capaEjecutiva: false,
  },
];

export const CATEGORIA_LABELS: Record<Categoria, string> = {
  tecnicos:       "1. Técnicos y Operativos",
  adopcion:       "2. Adopción y Uso",
  calidad_datos:  "3. Calidad de Datos e Interoperabilidad",
  asistenciales:  "4. Asistenciales",
  financieros:    "5. Financieros y Ciclo de Ingresos",
  seguridad:      "6. Seguridad y Cumplimiento",
  gobierno:       "7. Gobierno y Soporte",
};

export const CATEGORIA_ORDER: ReadonlyArray<Categoria> = [
  "tecnicos", "adopcion", "calidad_datos",
  "asistenciales", "financieros", "seguridad", "gobierno",
];

export function kpisByCategoria(categoria: Categoria): KpiDefinition[] {
  return KPI_CATALOG.filter((k) => k.categoria === categoria);
}

export function getKpiById(id: string): KpiDefinition | undefined {
  return KPI_CATALOG.find((k) => k.id === id);
}
